<?php
$servicePage = [
  'slug' => 'ai-seo-services-aeo-geo-llm-seo',
  'pageTitle' => 'AI SEO Services (AEO / GEO / LLM SEO) | Optimizers UAE',
  'pageDescription' => 'AI SEO services that get UAE businesses cited by ChatGPT, Google AI Overviews and Perplexity.',
  'categoryLabel' => 'SEO',
  'heroIcon' => 'assets/icons/brand/google.svg',
  'heroArtwork' => 'assets/images/service-pages/optimizers-next-gen-ai-visibility.svg',
  'heroArtworkAlt' => 'Next-generation AI visibility preview',
  'heroEyebrow' => 'AI SEO SERVICES (AEO / GEO / LLM SEO)',
  'heroHeading' => 'AI SEO Services That Get Your Business Cited by ChatGPT, Google AI Overviews, and Perplexity',
  'heroHeadingMuted' => '',
  'heroDescription' => 'More UAE customers are starting their research inside AI tools instead of typing directly into Google. We track where your business currently appears in AI-generated answers, close the gaps holding you back, and build the entity authority that determines whether AI tools trust your business enough to cite it.',
  'auditLabel' => 'Get a Free AI SEO Audit',
  'heroMeta' => ['CHATGPT · GEMINI · PERPLEXITY', 'AEO · GEO · LLM'],
  'overviewEyebrow' => 'WHAT IS AI SEO',
  'overviewHeading' => 'AI SEO,',
  'overviewHeadingMuted' => 'Explained Simply.',
  'overviewCopy' => 'AI SEO, also called AEO, GEO, or LLM SEO, is the practice of optimizing your online presence to be cited directly inside AI-generated answers from tools like ChatGPT, Google AI Overviews, Perplexity, and Gemini, not just traditional search results. Its specific job is monitoring where you currently stand, finding the gaps, and building the entity authority that makes AI tools trust your business enough to mention it.',
  'stats' => [['value'=>'200+', 'label'=>'UAE Clients'], ['value'=>'5.0', 'label'=>'Google Rating']],
  'includedHeading' => 'AI SEO Services',
  'includedHeadingMuted' => 'Built for AI Visibility.',
  'includedCopy' => 'A focused service covering monitoring, gap analysis, entity consistency, and platform-specific visibility.',
  'included' => [['title'=>'AI Citation Monitoring & Tracking', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'AI Platform-Specific Strategy', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Direct-Answer Gap Auditing', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Entity & Brand Consistency for AI Recognition', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'AI Overview Opportunity Research', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Knowledge Panel & Entity Optimization', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Multi-Platform Visibility Strategy', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Competitor AI Visibility Benchmarking', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>'']],
  'whyHeading' => 'Why AI SEO Matters',
  'whyHeadingMuted' => 'for Your UAE Business.',
  'why' => [['title'=>'Reaches Customers Before They Even Open Google', 'copy'=>'More research now starts directly inside AI chat tools, skipping traditional search for an increasing share of queries.'], ['title'=>'Stronger Keyword Relevance', 'copy'=>'Being cited by an AI tool functions like a built-in recommendation and can carry significant trust with the user.'], ['title'=>'A Real Advantage While Competitors Catch Up', 'copy'=>'Many agencies have not started tracking or optimizing for AI citation yet, leaving opportunity for businesses that move early.'], ['title'=>'Strengthens Your Traditional Search Authority Too', 'copy'=>'The entity consistency and content depth AI SEO builds can reinforce traditional search authority as well.']],
  'processHeading' => 'How We Approach AI SEO SERVICES',
  'processHeadingMuted' => 'for UAE Businesses.',
  'process' => [['title'=>'AI Visibility Audit', 'copy'=>'We check where and how often your business currently appears across major AI tools for your key topics.'], ['title'=>'Gap Analysis', 'copy'=>'We identify which questions and topics you’re missing from AI-generated answers.'], ['title'=>'Entity & Authority Building', 'copy'=>'We strengthen brand consistency and credibility signals AI tools rely on to trust a source.'], ['title'=>'Content Coordination', 'copy'=>'We work alongside semantic content writing and technical SEO to close gaps with properly structured, citable content.'], ['title'=>'Ongoing Monitoring', 'copy'=>'We track citation rate and AI visibility monthly as the space evolves.']],
  'faqHeading' => 'AI SEO Services Questions',
  'faqHeadingMuted' => 'From UAE Business Owners.',
  'faqs' => [['question'=>'What is the difference between AI SEO, AEO, and GEO?', 'answer'=>'They overlap heavily and are often used interchangeably. AEO and GEO describe optimizing content to be cited by AI-generated answers, while AI SEO is the broader umbrella term including LLM-specific optimization.'], ['question'=>'How do you actually track whether my business is being cited by AI tools?', 'answer'=>'We run structured queries across major AI tools for your key topics and questions, recording whether and how your business appears, then track this over time.'], ['question'=>'Does AI SEO replace traditional SEO?', 'answer'=>'No. AI SEO works alongside traditional SEO. Strong technical SEO and well-written content remain the foundation, while AI SEO adds monitoring and entity-building work specific to AI citation.'], ['question'=>'Why does brand consistency matter for AI tools specifically?', 'answer'=>'AI tools rely on consistent facts about your business appearing across the web to build confidence in citing you accurately.'], ['question'=>'Can a small UAE business realistically compete for AI citations against bigger brands?', 'answer'=>'Yes. AI tools can favor clear, specific, well-structured answers, giving a smaller business that covers a niche thoroughly a chance to get cited.'], ['question'=>'How much does AI SEO cost in the UAE?', 'answer'=>'AI SEO services typically start from AED 2,000 to AED 3,500 per month, often layered on top of an existing SEO or content retainer.']],
  'related' => [['title'=>'Off Page SEO', 'url'=>'off-page-seo.php'], ['title'=>'On Page SEO', 'url'=>'on-page-seo.php'], ['title'=>'AI SEO', 'url'=>'ai-seo-services-aeo-geo-llm-seo.php'], ['title'=>'International SEO', 'url'=>'international-seo.php'], ['title'=>'Local SEO', 'url'=>'local-seo-service.php'], ['title'=>'E-Commerce SEO', 'url'=>'e-commerce-seo-services.php'], ['title'=>'Technical SEO', 'url'=>'technical-seo.php']],
  'ctaHeading' => 'Ready to Show Up in AI-Generated Answers?',
  'ctaHeadingMuted' => '',
  'ctaCopy' => 'Get a free AI visibility check showing exactly where your business stands across ChatGPT, Google AI Overviews, and Perplexity right now.',
];
require __DIR__ . '/service-page-template.php';