<?php
$servicePage = [
  'slug' => 'content-creation-reels',
  'pageTitle' => 'Content Creation & Reels in Dubai | Optimizers UAE',
  'pageDescription' => 'Content creation and Reels production in Dubai for UAE brands, including strategy, scripting, shoots, editing, captions, and platform-ready delivery.',
  'categoryLabel' => 'Branding & Design',
  'heroIcon' => 'assets/icons/brand/instagram.svg',
  'heroArtwork' => 'assets/images/service-pages/content-studio-card.svg',
  'heroArtworkAlt' => 'Content creation studio workflow',
  'heroEyebrow' => 'Content Creation & Reels Services',
  'heroHeading' => 'Content Creation & Reels in Dubai',
  'heroHeadingMuted' => 'That Get UAE Audiences to Stop Scrolling and Start Engaging',
  'heroDescription' => 'Short-form video is where UAE audiences spend the majority of their social media time, and businesses that show up consistently with strong content build trust faster than any other channel. We handle the entire content creation process in Dubai from scripting and shooting to editing and delivery, producing Instagram Reels, TikTok videos, and social media content that represents your brand properly and performs on the platforms your customers use every day.',
  'auditLabel' => 'Get a Free Content Creation Consultation',
  'heroMeta' => ['CONTENT STUDIO · SCRIPTING · SHOOT · EDIT', 'REELS · TIKTOK · YOUTUBE SHORTS'],
  'overviewEyebrow' => 'What Is Content Creation?',
  'overviewHeading' => 'Content Creation & Reels,',
  'overviewHeadingMuted' => 'Explained Simply.',
  'overviewCopy' => 'Content creation is the end-to-end process of producing short-form video content for social media platforms, from scripting and storyboarding through on-location or studio production, editing, captioning, and delivery ready for upload. A professional content creator in Dubai handles the entire pipeline so your brand shows up consistently with video content creation that actually looks like it belongs on the platform, feels native to how UAE audiences browse, and does not look like a corporate advertisement that people skip within two seconds.',
  'stats' => [
    ['value' => '200+', 'label' => 'UAE Clients'],
    ['value' => '7', 'label' => 'Emirates Covered'],
  ],
  'includedHeading' => 'What Our Content Creation & Reels',
  'includedHeadingMuted' => 'Service Covers.',
  'includedCopy' => 'Every piece of content is produced from brief to delivery as a complete service, not handed back as raw footage for your team to figure out.',
  'included' => [
    ['title' => 'Instagram Reels, TikTok & YouTube Shorts Production', 'icon' => 'assets/icons/brand/instagram.svg', 'copy' => 'End-to-end short-form video production for every major platform, shot and edited natively for each platform’s format, aspect ratio, and audience behavior so the content feels like it belongs there.'],
    ['title' => 'Script Writing & Content Storytelling', 'icon' => 'assets/icons/brand/medium.svg', 'copy' => 'We write scripts and content frameworks that hook the viewer in the first two seconds and hold attention through to the call to action, built around your brand voice and what your UAE audience actually responds to.'],
    ['title' => 'On-Location & Studio Shoots', 'icon' => 'assets/icons/service-pages/mobile.svg', 'copy' => 'We shoot at your premises, across locations in Dubai and the UAE, or in a studio setup depending on the brief, with full production direction so your team does not need to manage the shoot themselves.'],
    ['title' => 'Motion Graphics & Text Animation', 'icon' => 'assets/icons/service-pages/code.svg', 'copy' => 'On-screen text, animated captions, lower thirds, and motion graphic elements added in post-production so the content performs correctly even when viewed on mute, which is how most UAE social media users watch video.'],
    ['title' => 'UGC-Style & Authentic Content', 'icon' => 'assets/icons/brand/tiktok.svg', 'copy' => 'User-generated content styled videos that feel organic and personal rather than overly produced, the format that currently generates the strongest engagement and trust signals across Instagram and TikTok in the UAE market.'],
    ['title' => 'Content Calendar Planning', 'icon' => 'assets/icons/service-pages/support.svg', 'copy' => 'We map out a month of content topics, formats, and posting cadence across your platforms so every piece of content serves a strategic purpose rather than being produced reactively when the last post runs out.'],
    ['title' => 'Platform-Optimized Editing & Captioning', 'icon' => 'assets/icons/brand/youtube.svg', 'copy' => 'Every video is edited to the correct duration, aspect ratio, and pacing for its destination platform, with subtitles added as standard since the majority of UAE social media viewers watch without sound.'],
    ['title' => 'Delivery Ready for Upload', 'icon' => 'assets/icons/ui/right-arrow.svg', 'copy' => 'Final exports delivered in the correct format and resolution for each platform, with captions, thumbnails, and posting notes prepared so your social media team can upload without any additional preparation.'],
  ],
  'whyHeading' => 'Why Content Creation & Reels Matter',
  'whyHeadingMuted' => 'for Your UAE Business.',
  'why' => [
    ['title' => 'Short-Form Video Is Where UAE Audiences Actually Are', 'copy' => 'The UAE has one of the highest per-capita social media usage rates in the world. Short-form video on Instagram and TikTok is where the attention is concentrated, and businesses that show up consistently there build awareness faster than almost any other channel available.'],
    ['title' => 'Reels Get More Organic Reach Than Any Other Format', 'copy' => 'Instagram and TikTok’s algorithms currently give Reels and short-form video significantly more organic distribution than static posts, meaning well-produced video content reaches audiences your business has not paid to advertise to yet.'],
    ['title' => 'Consistent Content Builds Trust Over Time', 'copy' => 'A UAE business that shows up in its customers’ feeds regularly with useful, relevant, well-made content builds a level of familiarity and trust that paid advertising on its own cannot replicate, no matter how large the budget.'],
    ['title' => 'One Shoot Produces Content Across Multiple Platforms', 'copy' => 'A single well-planned production session produces Instagram Reels, TikTok videos, YouTube Shorts, and story content simultaneously, making content creation far more efficient than producing each format separately.'],
  ],
  'processHeading' => 'How We Handle Content Creation & Reels Production',
  'processHeadingMuted' => 'for UAE Brands.',
  'process' => [
    ['title' => 'Content Strategy & Brief', 'copy' => 'We define your content goals, target audience on each platform, tone of voice, key messages, and monthly content themes before any production begins, so every video serves a purpose.'],
    ['title' => 'Scripting & Storyboarding', 'copy' => 'We write scripts and storyboard each video so the content structure, hook, key message, and call to action are locked before the shoot, removing guesswork and wasted footage from the production day.'],
    ['title' => 'Production & Shoot', 'copy' => 'We shoot on location or in studio with full creative direction, handling everything from framing and lighting to talent direction, so your team shows up to a shoot that runs smoothly rather than one that wastes half the day on setup.'],
    ['title' => 'Editing & Post-Production', 'copy' => 'We edit every piece of content with platform-native pacing, add motion graphics, on-screen text, subtitles, and audio treatment, then review internally before it goes to you for approval.'],
    ['title' => 'Delivery & Scheduling Support', 'copy' => 'We deliver final exports ready for upload alongside a posting schedule and any platform-specific notes your social media team needs, so content goes live on time without additional back-and-forth.'],
  ],
  'faqHeading' => 'Content Creation & Reels Questions',
  'faqHeadingMuted' => 'From UAE Business Owners.',
  'faqs' => [
    ['question' => 'What is the difference between content creation and video editing?', 'answer' => 'Content creation is the full end-to-end process of producing video content from scratch, covering strategy, scripting, production, and editing. Video editing is the post-production step only, working with footage that already exists. If you have no footage yet and need someone to script, shoot, and produce your social media videos, content creation is the right service. If you have raw footage that needs cutting, grading, and finishing, video editing is the service you need.'],
    ['question' => 'Do you handle the filming or just the editing?', 'answer' => 'We handle the complete production pipeline from script to delivered file. This includes writing the script, planning the shoot, on-location or studio filming with our production team, and full post-production editing. If you already have footage and only need editing, that is a separate service covered under our Video Editing offering.'],
    ['question' => 'How many Reels or videos can you produce per month?', 'answer' => 'Monthly output is scoped based on your content calendar and budget and is confirmed in your proposal before any work begins. Most UAE businesses on a regular content retainer produce between 8 and 20 short-form videos per month depending on how many platforms they publish to and the complexity of each piece. We recommend starting with a clear monthly content plan rather than a fixed number so every video produced has a strategic reason to exist.'],
    ['question' => 'Can you create content for both TikTok and Instagram simultaneously from the same shoot?', 'answer' => 'Yes. We plan every production session to capture content that works across both platforms from a single shoot, accounting for the different aspect ratios, pacing preferences, and caption lengths each platform favors. One well-planned production day produces platform-native content for Instagram Reels, TikTok, YouTube Shorts, and stories simultaneously rather than producing each separately.'],
    ['question' => 'How much does content creation cost in Dubai?', 'answer' => 'Content creation services in Dubai are typically priced as a monthly retainer based on the number of videos produced, number of platforms covered, and whether production involves studio time or location shoots. Most content creation companies in the UAE, including Optimizers, provide a custom monthly proposal based on your specific content volume and production requirements rather than a fixed price per video, since the scope varies significantly between clients. We confirm all costs before any work begins.'],
  ],
  'related' => [
    ['title' => 'Business Branding & Designing', 'url' => 'business-branding-designing.php'],
    ['title' => 'Graphic Designing', 'url' => 'graphic-designing.php'],
    ['title' => 'Video Editing', 'url' => 'video-editing.php'],
    ['title' => 'Social Media Marketing', 'url' => 'index.php#social-media-marketing'],
  ],
  'ctaHeading' => 'Ready to Show Up on Social Media',
  'ctaHeadingMuted' => 'With Content That Actually Works?',
  'ctaCopy' => 'Get a free content consultation and we will show you exactly how we would approach your brand’s content strategy, production calendar, and monthly output across Instagram, TikTok, and beyond.',
];

require __DIR__ . '/service-page-template.php';
