<?php
$servicePage = [
  'slug' => 'custom-web-development',
  'pageTitle' => 'Custom Web Development Company Dubai | UAE | Optimizers',
  'pageDescription' => 'Custom web development services in Dubai for bespoke websites, web applications, portals, booking systems, dashboards, API integrations, and scalable fully owned code.',
  'heroIcon' => 'assets/icons/service-pages/code.svg',
  'heroEyebrow' => 'Custom Web Development Service',
  'heroHeading' => 'Custom Web Development in Dubai',
  'heroHeadingMuted' => 'When WordPress or Shopify Simply Cannot Do What You Need',
  'heroDescription' => 'Not every UAE business requirement fits inside a CMS or an e-commerce platform. When your project needs a booking engine built around your specific workflow, a client portal with custom logic, a web application that integrates multiple systems, or a bespoke tool your industry has never seen built before, our custom web development company in Dubai builds it from scratch with clean, scalable, fully owned code.',
  'auditLabel' => 'Get a Free Custom Web Development Audit',
  'heroMeta' => ['YOURWEBAPP.AE · CUSTOM CODE · SCALABLE', 'API INTEGRATION · FAST & SECURE'],
  'overviewEyebrow' => 'What Is Custom Development?',
  'overviewHeading' => 'Custom Web Development,',
  'overviewHeadingMuted' => 'Explained Simply.',
  'overviewCopy' => 'Custom web development is the process of building a website, web application, or digital system entirely from scratch, using code written specifically for your project rather than configured from an existing platform like WordPress or Shopify. It is the right choice when your business has requirements that go beyond what any standard platform can handle cleanly, whether that is a complex booking system with custom availability logic, a client or agent portal with role-based access, a multi-vendor marketplace, or a web application that needs to connect and synchronize multiple third-party systems in real time. The result is a product built entirely around your business process, with no platform limitations, no unnecessary features, and no licensing fees to a third party.',
  'stats' => [
    ['value' => '200+', 'label' => 'UAE Clients'],
    ['value' => '5.0', 'label' => 'Google Rating'],
  ],
  'includedHeading' => 'What Our Custom Web Development',
  'includedHeadingMuted' => 'Service Covers.',
  'includedCopy' => 'Every custom development project is scoped individually, but these are the core disciplines our development team covers across every build.',
  'included' => [
    ['title' => 'Custom Front-End Development', 'icon' => 'assets/icons/service-pages/code.svg'],
    ['title' => 'Custom Back-End Development', 'icon' => 'assets/icons/service-pages/code.svg'],
    ['title' => 'Database Architecture & Setup', 'icon' => 'assets/icons/service-pages/code.svg'],
    ['title' => 'API Development & Third-Party Integrations', 'icon' => 'assets/icons/service-pages/code.svg'],
    ['title' => 'Custom Admin Panel & Dashboard Development', 'icon' => 'assets/icons/service-pages/support.svg'],
    ['title' => 'Web Application & Portal Development', 'icon' => 'assets/icons/service-pages/mobile.svg'],
    ['title' => 'Performance, Security & Infrastructure', 'icon' => 'assets/icons/service-pages/support.svg'],
    ['title' => 'Deployment, Documentation & Technical Handover', 'icon' => 'assets/icons/service-pages/support.svg'],
  ],
  'whyHeading' => 'Why Custom Web Development in Dubai',
  'whyHeadingMuted' => 'Is the Right Choice for Complex Requirements.',
  'why' => [
    ['title' => 'No Platform Limitations', 'copy' => 'WordPress and Shopify are excellent platforms for what they do, but both have architectural ceilings. Custom development removes those ceilings entirely, so the application does exactly what your business logic requires without workarounds or plugin stacks that break over time.'],
    ['title' => 'Built Around Your Process, Not Around a Template', 'copy' => 'Every workflow, every user journey, and every data structure is designed specifically around how your business operates, not adapted from how a platform was built to work for the broadest possible audience.'],
    ['title' => 'You Own Everything', 'copy' => 'No platform dependency, no licensing fees, no risk of a third-party platform changing pricing or discontinuing a feature your business relies on. You own the code, the database, and the infrastructure outright.'],
    ['title' => 'Scales as Your Business Grows', 'copy' => 'A properly architected custom build scales with your user volume and feature requirements without the performance ceiling or structural limitations that come with building complex features on top of a platform it was not designed for.'],
  ],
  'processHeading' => 'How We Approach',
  'processHeadingMuted' => 'Custom Web Development Projects.',
  'process' => [
    ['title' => 'Discovery & Technical Scoping', 'copy' => 'We map every feature, user role, data flow, and integration requirement before writing a line of code, producing a technical specification document that becomes the project’s source of truth and prevents scope changes mid-build.'],
    ['title' => 'Architecture & System Design', 'copy' => 'We design the database structure, application architecture, and API layer before development begins, making decisions that affect performance and scalability at the right stage rather than trying to retrofit them later.'],
    ['title' => 'Front-End & Back-End Development', 'copy' => 'We build both the user-facing interface and the server-side logic in parallel, with regular internal build reviews and client milestone checkpoints so nothing drifts from the original specification.'],
    ['title' => 'QA Testing & Security Review', 'copy' => 'We run functional testing across every user journey, load testing against expected traffic volumes, and a security review covering data access, input validation, and infrastructure configuration before any production deployment.'],
    ['title' => 'Deployment, Documentation & Handover', 'copy' => 'We deploy to your hosting environment, write technical documentation covering every part of the system, and transfer full ownership of the codebase, so your team or any future developer can maintain and extend the application independently.'],
  ],
  'faqHeading' => 'Custom Development Questions',
  'faqHeadingMuted' => 'From UAE Business Owners.',
  'faqs' => [
    ['question' => 'When do I need custom development instead of WordPress or Shopify?', 'answer' => 'Custom development becomes the right choice when your requirements genuinely cannot be met cleanly by an existing platform. Clear signals include needing role-based user access with different data views per user type, complex workflow logic that does not map to standard CMS or e-commerce flows, real-time data synchronization between multiple external systems, or a product that is itself a web application rather than a content site or online store. If you are unsure, we assess your requirements during a discovery call and recommend the most appropriate approach honestly, including whether a platform like WordPress or Shopify would actually serve you better.'],
    ['question' => 'What technologies do you use for custom development projects?', 'answer' => 'The technology stack is selected around the project’s functionality, scale, integrations, and long-term maintenance needs. Front-end development may use React, Vue, or vanilla JavaScript. Back-end systems may use PHP, Node.js, or Python, while relational data is commonly handled with MySQL or PostgreSQL and Redis can be used for caching on high-traffic applications.'],
    ['question' => 'Will we own the code once the project is complete?', 'answer' => 'Yes. At handover, you receive ownership of the custom codebase, repository, database, technical documentation, and infrastructure configuration created for the project. Your business is not locked into Optimizers or another vendor and can appoint any capable development team to maintain or extend the application.'],
    ['question' => 'How long does a custom web development project take in Dubai?', 'answer' => 'Timeline depends on the approved technical scope. A focused web application with a clearly defined feature set typically takes 8 to 14 weeks from specification approval to deployment. Larger platforms, marketplaces, or systems with multiple integrations commonly take 16 to 24 weeks. The final timeline is documented in the project proposal before development begins.'],
    ['question' => 'How much does custom website development cost in Dubai?', 'answer' => 'Custom web development cost in Dubai depends on feature complexity, user roles, data structure, third-party integrations, security requirements, infrastructure, and ongoing hosting or maintenance scope. After the technical scoping session, we provide a fixed-price proposal with a complete feature breakdown so the total custom website development cost is clear before work begins.'],
  ],
  'ctaHeading' => 'Have a Project That Needs',
  'ctaHeadingMuted' => 'to Be Built From Scratch?',
  'ctaCopy' => 'Tell us what you need to build. We will assess your requirements, tell you whether custom development is genuinely the right approach, and give you a clear fixed-price proposal if it is.',
];

require __DIR__ . '/service-page-template.php';
