<?php
$servicePage = [
  'slug' => 'e-commerce-seo-services',
  'pageTitle' => 'E-Commerce SEO Services in Dubai | UAE | Optimizers',
  'pageDescription' => 'E-Commerce SEO services built for UAE online stores.',
  'categoryLabel' => 'SEO',
  'heroIcon' => 'assets/icons/brand/google.svg',
  'heroArtwork' => 'assets/images/service-pages/optimizers-seo-search-ranking.svg',
  'heroArtworkAlt' => 'E-commerce SEO search ranking preview',
  'heroEyebrow' => 'E-COMMERCE SEO SERVICES',
  'heroHeading' => 'E-Commerce SEO Services Built for UAE Online Stores',
  'heroHeadingMuted' => '',
  'heroDescription' => 'Online stores have SEO problems a regular website never runs into, thousands of near-duplicate product variants, filtered category URLs, and out-of-stock pages bleeding authority. We optimize product pages, category structure, and the technical setup unique to e-commerce so your UAE store ranks for buyers, not just gets indexed.',
  'auditLabel' => 'Get a Free E-Commerce SEO Audit',
  'heroMeta' => ['PRODUCTS · CATEGORIES · SCHEMA · MERCHANT CENTER', '+230% ORGANIC TRAFFIC · #1 PRODUCT RANK'],
  'overviewEyebrow' => 'WHAT IS E-COMMERCE SEO',
  'overviewHeading' => 'E-Commerce SEO,',
  'overviewHeadingMuted' => 'Explained Simply.',
  'overviewCopy' => 'E-commerce SEO is the practice of optimizing an online store’s product pages, category pages, and technical structure so it ranks for the exact terms shoppers search before buying. It builds on standard on-page SEO but solves problems unique to online stores, duplicate content from size and color variants, filtered navigation creating thousands of near-identical URLs, and product schema that helps listings show prices and reviews directly in search results.',
  'stats' => [['value'=>'200+', 'label'=>'UAE Clients'], ['value'=>'5.0', 'label'=>'Google Rating']],
  'includedHeading' => 'What Our E-Commerce SEO Service',
  'includedHeadingMuted' => 'Covers.',
  'includedCopy' => 'Every page we touch goes through the same complete checklist, not a partial pass.',
  'included' => [['title'=>'Product Page Optimization', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Category & Collection Page SEO', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Faceted Navigation & Filter Cleanup', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Product Schema Markup', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Variant Duplicate Content Management', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Out-of-Stock & Discontinued Product Handling', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Internal Linking for Product Discovery', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Google Merchant Center Feed Optimization', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>'']],
  'whyHeading' => 'Why E-Commerce SEO Matters',
  'whyHeadingMuted' => 'for Your UAE Business.',
  'why' => [['title'=>'Captures Buyers at Every Stage', 'copy'=>'Category pages catch shoppers still browsing, product pages catch shoppers ready to buy, and both need different optimization.'], ['title'=>'Stops Wasted Crawl Budget', 'copy'=>'Fixing duplicate variant and filter pages means Google spends crawl attention on pages that actually convert.'], ['title'=>'Helps You Compete With Marketplaces', 'copy'=>'Strong product page SEO can help a UAE store compete with marketplace listings for branded or niche searches.'], ['title'=>'Strengthens Google Shopping Performance Too', 'copy'=>'Clean, optimized product data can improve how listings perform in paid Shopping campaigns as well.']],
  'processHeading' => 'How We Approach E-Commerce SEO',
  'processHeadingMuted' => 'for UAE Businesses.',
  'process' => [['title'=>'Store & Catalog Audit', 'copy'=>'We review your product and category structure, identifying duplicate content and technical issues unique to your platform.'], ['title'=>'Keyword Mapping by Product', 'copy'=>'We assign target keywords to the right product and category pages based on search volume and intent.'], ['title'=>'On-Page & Schema Implementation', 'copy'=>'We optimize titles, descriptions, and structured data product by product.'], ['title'=>'Technical Cleanup', 'copy'=>'We fix faceted navigation, canonical tags, and variant duplication issues specific to your store platform.'], ['title'=>'Monitoring & Scaling', 'copy'=>'We track product and category rankings monthly and extend the strategy as your catalog grows.']],
  'faqHeading' => 'E-Commerce SEO Questions',
  'faqHeadingMuted' => 'From UAE Business Owners.',
  'faqs' => [['question'=>'How is e-commerce SEO different from regular on-page SEO?', 'answer'=>'E-commerce SEO applies on-page SEO principles to product and category pages while solving store-specific problems such as variant duplication and filtered navigation.'], ['question'=>'How do you handle duplicate content from product variants?', 'answer'=>'We use canonical tags and structured URL strategies so variant pages point search engines to the correct primary version.'], ['question'=>'Can e-commerce SEO help me compete with marketplaces like Amazon or noon?', 'answer'=>'It can meaningfully improve competitiveness, particularly for branded or niche products, although marketplaces have an inherent scale advantage for broad searches.'], ['question'=>'Does e-commerce SEO work for Shopify stores specifically?', 'answer'=>'Yes. We work with Shopify’s URL structure, app ecosystem, and theme limitations alongside WooCommerce and other major platforms.'], ['question'=>'How much does e-commerce SEO cost in the UAE?', 'answer'=>'E-commerce SEO typically starts from AED 3,000 to AED 5,000 per month depending on catalog size.']],
  'related' => [['title'=>'Off Page SEO', 'url'=>'off-page-seo.php'], ['title'=>'On Page SEO', 'url'=>'on-page-seo.php'], ['title'=>'AI SEO', 'url'=>'ai-seo-services-aeo-geo-llm-seo.php'], ['title'=>'International SEO', 'url'=>'international-seo.php'], ['title'=>'Local SEO', 'url'=>'local-seo-service.php'], ['title'=>'E-Commerce SEO', 'url'=>'e-commerce-seo-services.php'], ['title'=>'Technical SEO', 'url'=>'technical-seo.php']],
  'ctaHeading' => 'Ready to Turn Your Store\'s Traffic Into Sales?',
  'ctaHeadingMuted' => '',
  'ctaCopy' => 'Get a free e-commerce SEO audit showing exactly which product and category pages are losing visibility right now.',
];
require __DIR__ . '/service-page-template.php';