<?php
$servicePage = [
  'slug' => 'google-ads',
  'pageTitle' => 'Google Ads in Dubai | UAE | Optimizers',
  'pageDescription' => 'Google Ads management services in Dubai for UAE businesses, including Search, Display, Shopping, YouTube, Performance Max and conversion tracking.',
  'categoryLabel' => 'Performance Marketing',
  'heroIcon' => 'assets/icons/brand/google-ads.svg',
  'heroArtwork' => 'assets/images/service-pages/google-ads-hero.svg',
  'heroArtworkAlt' => 'Google Ads search campaign preview',
  'heroEyebrow' => 'Google Ads Management Services',
  'heroHeading' => 'Google Ads in Dubai That Puts Your UAE Business in Front of Customers',
  'heroHeadingMuted' => 'Already Searching for What You Sell.',
  'heroDescription' => 'Every day, UAE customers type exactly what they want into Google and click the first relevant result they see. We manage Google Ads for UAE businesses that want to appear at that moment, not just in front of people who might be interested, but in front of people actively searching for their specific product or service right now. As a dedicated Google Ads agency in Dubai delivering Google Ads services and management across all seven emirates, we handle the complete campaign lifecycle from keyword research and ad copy through to bid strategy, conversion tracking, and the monthly reporting that shows exactly what every dirham of budget delivered.',
  'auditLabel' => 'Get a Free Google Ads Service',
  'heroMeta' => ['SEARCH · DISPLAY · SHOPPING · YOUTUBE · PERFORMANCE MAX', 'LEADS · SALES · CONVERSIONS'],
  'overviewEyebrow' => 'What Is Google Ads?',
  'overviewHeading' => 'Google Ads,',
  'overviewHeadingMuted' => 'Explained Simply.',
  'overviewCopy' => 'Google Ads, previously known as Google AdWords, is Google’s paid advertising platform covering search ads that appear when someone types a specific query into Google, Display Network banner ads that appear across millions of websites and apps, YouTube video ads, Google Shopping product listings, and Performance Max campaigns that distribute budget automatically across all of Google’s channels. Unlike social media advertising which intercepts people while they are doing something else, pay per click advertising on Google captures demand that already exists, people actively searching for what your UAE business sells, making it uniquely powerful for businesses that want to generate leads and sales from customers who are already in a buying mindset.',
  'stats' => [ ['value' => '200+', 'label' => 'UAE Clients'], ['value' => '7', 'label' => 'Emirates Covered'] ],
  'includedHeading' => 'What Our Google Ads Management Service',
  'includedHeadingMuted' => 'Covers.',
  'includedCopy' => 'Every Google Ads campaign is built with a clear structure, properly tracked conversions, and active daily management, not a set-and-forget account that drains budget without anyone optimizing it.',
  'included' => [    ['title' => 'Google Search Ads Campaign Management', 'icon' => 'assets/icons/brand/google-ads.svg', 'copy' => 'We build and manage Google Search campaigns targeting the exact keywords UAE customers type when looking for your products or services, with ad copy written to maximize click-through rate and landing page alignment to maximize conversion rate from every click.'],
    ['title' => 'Google Display Network Advertising', 'icon' => 'assets/icons/brand/google-ads.svg', 'copy' => 'We run Google Display campaigns that show your banner ads across the millions of websites and apps in Google’s network, targeting UAE audiences by demographics, interests, and remarketing lists to build brand awareness and recapture visitors who did not convert on the first visit.'],
    ['title' => 'Google Shopping Ads for E-Commerce', 'icon' => 'assets/icons/brand/google-ads.svg', 'copy' => 'We manage paid Google Shopping campaigns for UAE e-commerce businesses, optimizing product feed data, bidding strategy, and campaign structure so your products appear prominently above organic search results for UAE shoppers ready to purchase.'],
    ['title' => 'YouTube Advertising', 'icon' => 'assets/icons/brand/youtube.svg', 'copy' => 'We build and manage YouTube video ad campaigns, from skippable in-stream ads and bumper ads to YouTube Shorts ads, targeting UAE audiences by demographics, interests, and search behavior to build brand awareness and drive consideration.'],
    ['title' => 'Performance Max Campaigns', 'icon' => 'assets/icons/brand/google-ads.svg', 'copy' => 'We set up and manage Google’s Performance Max campaign type, which uses Google’s AI to distribute budget across Search, Display, YouTube, Gmail, and Maps simultaneously, optimizing in real time toward your defined conversion goals.'],
    ['title' => 'Keyword Research & Negative Keyword Management', 'icon' => 'assets/icons/brand/google-ads.svg', 'copy' => 'We conduct comprehensive PPC keyword research to identify the highest-intent, most commercially valuable terms your UAE customers search, and maintain an active negative keyword list that prevents your budget from being spent on irrelevant traffic.'],
    ['title' => 'Conversion Tracking & Google Analytics Setup', 'icon' => 'assets/icons/brand/google-ads.svg', 'copy' => 'We install and verify Google Ads conversion tracking, connect it to Google Analytics 4, and configure goals for every action that matters to your business, form submissions, phone calls, purchases, and WhatsApp clicks.'],
    ['title' => 'Monthly Reporting & Budget Optimization', 'icon' => 'assets/icons/brand/google-ads.svg', 'copy' => 'We provide clear monthly reports covering impressions, clicks, cost per click, conversions, cost per conversion, and ROAS alongside a transparent account of how we managed and optimized the budget throughout the month and what the plan is for the following month.'],
  ],
  'whyHeading' => 'Why Pay Per Click Advertising on Google Matters',
  'whyHeadingMuted' => 'for UAE Businesses.',
  'why' => [
    ['title' => 'Captures Customers at the Highest Point of Purchase Intent', 'copy' => 'Google advertising reaches UAE customers at the exact moment they are actively searching for what you sell, not interrupting them while they are doing something else. A well-placed search ad appears when someone types a high-intent query and is ready to act on the results they see.'],
    ['title' => 'Results Start Immediately Unlike SEO', 'copy' => 'Unlike organic search which builds over months, a properly configured Google Ads campaign can appear at the top of UAE search results on the day it launches, making it the fastest way to generate search-based leads and sales while longer-term SEO authority is being built in parallel.'],
    ['title' => 'Every Dirham Is Fully Accountable', 'copy' => 'A well-managed Google Ads company tracks exactly which keywords generated which leads and which campaigns produced which revenue, giving UAE business owners a level of budget accountability that most traditional advertising channels cannot match.'],
    ['title' => 'Scales Precisely With Your Business', 'copy' => 'Google Ads budget can be increased or decreased at any time based on business capacity, seasonal demand, or campaign performance, without any structural rebuild. A campaign performing well in one UAE emirate can be expanded to all seven within a single campaign management session.'],
  ],
  'processHeading' => 'How Our Google Ads Specialists Manage Campaigns',
  'processHeadingMuted' => 'for UAE Businesses.',
  'process' => [
    ['title' => 'Account Audit & Search Strategy', 'copy' => 'We audit your existing Google Ads account if one is in place, assessing current campaign structure, keyword coverage, Quality Scores, conversion tracking health, and historical performance data, then build a clear strategy covering campaign types, keyword targeting, and bid approach before any new budget is committed.'],
    ['title' => 'Keyword Research & Campaign Architecture', 'copy' => 'We conduct comprehensive keyword research specific to how UAE customers search for your products and services, build a logical campaign and ad group structure, write ad copy variants for testing, and configure the negative keyword list that prevents budget being wasted on irrelevant queries from day one.'],
    ['title' => 'Conversion Tracking & Analytics Setup', 'copy' => 'We install and verify every conversion action your campaign should optimize toward, form submissions, phone calls, purchases, WhatsApp button clicks, and key page visits, and connect the Google Ads account correctly to Google Analytics 4 before any spend begins.'],
    ['title' => 'Campaign Launch & Bid Management', 'copy' => 'We launch campaigns with the appropriate bidding strategy for your objective and account maturity, whether manual CPC during the data-gathering phase or Smart Bidding strategies once sufficient conversion data exists, monitoring performance daily and adjusting bids, budgets, and targeting as the data builds.'],
    ['title' => 'Ongoing Optimization & Monthly Reporting', 'copy' => 'We optimize continuously throughout every month, adding negative keywords from search term reports, testing new ad copy, refining audience targeting, adjusting bids by device and location, and pausing underperforming keywords, then delivering a clear monthly performance report and updated strategy for the following month.'],
  ],
  'faqHeading' => 'Google Ads Questions',
  'faqHeadingMuted' => 'From UAE Business Owners.',
  'faqs' => [
    ['question' => 'How is Google Ads different from social media advertising?', 'answer' => 'The core difference is intent. Social media ads interrupt people while they are browsing content and are not actively looking for anything, while Google Search ads appear when someone actively types a specific query and is already in a searching or buying mindset. Both have a place in a complete performance marketing strategy, but Google Search is typically the more direct path to capturing demand that already exists in the UAE market.'],
    ['question' => 'How much should I budget for Google Ads in the UAE?', 'answer' => 'The right budget depends on your industry, how competitive your target keywords are, and your campaign objective. Highly competitive sectors in the UAE such as real estate, legal services, and healthcare carry higher cost-per-click rates than less competitive niches. Most UAE businesses starting Google Ads generate enough conversion data to optimize properly with a minimum monthly ad spend in the range of AED 3,000 to AED 8,000, though the right figure for your specific keywords and industry is something we assess before any budget is committed.'],
    ['question' => 'How long does it take for Google Ads to start working?', 'answer' => 'A Google Ads campaign can generate impressions and clicks on the day it launches. However, campaigns using Google’s Smart Bidding strategies require a learning period of approximately 2 to 4 weeks to accumulate enough conversion data to optimize delivery effectively. Most UAE businesses see the campaign reaching efficient, stable performance within 4 to 8 weeks of launch when conversion tracking is properly configured from day one.'],
    ['question' => 'What is the difference between Google Search ads and Google Shopping ads?', 'answer' => 'Google Search ads are text-based ads that appear when someone searches a keyword, showing your headline, description, and website link in the search results. Google Shopping ads are product-specific listings that appear at the top of search results showing your product image, name, price, and store name, pulled from your Google Merchant Center product feed. Search ads suit service businesses and businesses selling through a website, while Shopping ads suit e-commerce businesses selling physical products.'],
    ['question' => 'How much does Google Ads management cost in Dubai?', 'answer' => 'Google Ads management services in Dubai are typically priced as a monthly management fee covering account strategy, keyword management, ad copy, bid optimization, and reporting, separate from your ad spend budget which goes directly to Google. Management fees vary based on the number of campaigns managed, the complexity of the account, and the volume of optimization work required each month. We provide a clear management fee proposal after the initial account audit.'],
  ],
  'relatedHeading' => 'Other Performance Marketing Services',
  'relatedHeadingMuted' => 'You May Need.',
  'related' => [
    ['title' => 'Google Ads', 'url' => 'google-ads.php'],
    ['title' => 'WhatsApp Marketing', 'url' => 'whatsapp-marketing.php'],
    ['title' => 'Email Marketing', 'url' => 'email-marketing.php'],
    ['title' => 'Social Media Marketing', 'url' => 'social-media-marketing.php'],
  ],
  'ctaHeading' => 'Ready to Appear at the Top of Google When UAE Customers Search for What You Sell?',
  'ctaHeadingMuted' => 'Let’s Build It Properly.',
  'ctaCopy' => 'Get a free Google Ads audit and we will show you exactly where your current account is losing budget, which keywords should be driving leads, and what a properly structured campaign would deliver for your UAE business.',
];
require __DIR__ . '/service-page-template.php';
