<?php
$servicePage = [
  'slug' => 'graphic-designing',
  'pageTitle' => 'Graphic Designing Services in Dubai | Optimizers UAE',
  'pageDescription' => 'Graphic designing services in Dubai for UAE businesses, including logos, social media graphics, marketing collateral, ad creative, presentations, and print design.',
  'categoryLabel' => 'Branding & Design',
  'heroIcon' => 'assets/icons/brand/adobe-illustrator.svg',
  'heroArtwork' => 'assets/images/service-pages/brand-design-preview.svg',
  'heroArtworkAlt' => 'Brand and graphic design preview',
  'heroEyebrow' => 'Graphic Designing Services',
  'heroHeading' => 'Graphic Designing in Dubai',
  'heroHeadingMuted' => 'That Makes UAE Businesses Look Like the Best in Their Industry',
  'heroDescription' => 'First impressions in the UAE market are made visually, before a single word gets read. We create logos, social media graphics, marketing collateral, and brand visuals for UAE businesses that communicate professionalism and build instant trust with customers. As a dedicated graphic designing services provider in Dubai working with UAE businesses across all seven emirates, our design team combines creative direction with a deep understanding of what resonates with audiences in this market.',
  'auditLabel' => 'Get a Free Design Consultation',
  'heroMeta' => ['BRAND IDENTITY · ILLUSTRATOR · PHOTOSHOP', 'FIGMA · INDESIGN · PRINT READY'],
  'overviewEyebrow' => 'What Is Graphic Designing?',
  'overviewHeading' => 'Graphic Designing,',
  'overviewHeadingMuted' => 'Explained Simply.',
  'overviewCopy' => 'Graphic designing is the process of creating visual content that communicates a message, builds brand recognition, and influences how people perceive a business. It covers everything from logo creation and brand identity visuals to social media graphics, marketing collateral, digital ad creatives, and print materials. For UAE businesses, professional graphic design is not a cosmetic upgrade, it is what separates brands customers instinctively trust from those they scroll past without a second look.',
  'stats' => [
    ['value' => '200+', 'label' => 'UAE Clients'],
    ['value' => '7', 'label' => 'Emirates Covered'],
  ],
  'includedHeading' => 'What Our Graphic Designing',
  'includedHeadingMuted' => 'Service Covers.',
  'includedCopy' => 'Every design deliverable is created from scratch for your brand, not adapted from a template bank used across other clients.',
  'included' => [
    ['title' => 'Logo Design & Brand Mark Creation', 'icon' => 'assets/icons/brand/adobe-illustrator.svg', 'copy' => 'Primary logo, icon variant, and alternate lockups delivered in all formats for print and digital use.'],
    ['title' => 'Social Media Graphics', 'icon' => 'assets/icons/brand/instagram.svg', 'copy' => 'On-brand post templates, story formats, and ad creatives sized for every platform your team publishes on.'],
    ['title' => 'Marketing Collateral Design', 'icon' => 'assets/icons/service-pages/support.svg', 'copy' => 'Brochures, flyers, banners, and promotional materials built to represent your brand at its best across every channel.'],
    ['title' => 'Digital Ad Creative', 'icon' => 'assets/icons/brand/google.svg', 'copy' => 'Banner ads, Google Display creatives, and Meta ad visuals designed to stop the scroll and drive click-through in competitive UAE markets.'],
    ['title' => 'Presentation & Pitch Deck Design', 'icon' => 'assets/icons/service-pages/mobile.svg', 'copy' => 'Investor decks, corporate presentations, and proposal documents designed to look as strong as the content they carry.'],
    ['title' => 'Infographic Design', 'icon' => 'assets/icons/service-pages/code.svg', 'copy' => 'Data, processes, and complex information translated into clear, visually engaging infographics that communicate quickly.'],
    ['title' => 'Print Design', 'icon' => 'assets/icons/brand/adobe-illustrator.svg', 'copy' => 'Business cards, signage, packaging, and any print material prepared to print production standards with correct bleed, colour profiles, and file formats.'],
    ['title' => 'File Delivery in All Formats', 'icon' => 'assets/icons/ui/right-arrow.svg', 'copy' => 'Source files (AI, PSD, Figma), high-resolution exports (PNG, PDF, JPG), and web-optimized versions delivered together at handover.'],
  ],
  'whyHeading' => 'Why Graphic Design Matters',
  'whyHeadingMuted' => 'for Your UAE Business.',
  'why' => [
    ['title' => 'First Impressions Are Made Visually', 'copy' => 'UAE customers decide whether to trust a business within seconds of seeing its visuals, long before they read a single word of content.'],
    ['title' => 'Consistency Builds Recognition', 'copy' => 'Businesses with consistent visual branding across every channel are significantly more recognizable and trusted than those with uncoordinated design.'],
    ['title' => 'Better Creative Drives Better Results', 'copy' => 'Ad creative quality is one of the strongest variables in paid campaign performance. Strong graphic design directly improves click-through rates, reduces cost per lead, and makes every dirham spent on advertising work harder.'],
    ['title' => 'Positions You Against Much Larger Competitors', 'copy' => 'Professional graphic design closes the visual gap between a growing UAE business and established enterprise brands, making presentation quality and business size feel much less relevant to a potential customer.'],
  ],
  'processHeading' => 'How We Approach Graphic Design',
  'processHeadingMuted' => 'for UAE Businesses.',
  'process' => [
    ['title' => 'Brief & Discovery', 'copy' => 'We learn your brand, industry, target audience, and exactly what each design deliverable needs to achieve before any creative work begins, so nothing is produced in the wrong direction.'],
    ['title' => 'Concept Development', 'copy' => 'We develop initial design directions grounded in your brief and present them for review, so the final creative direction is chosen with confidence rather than guessed at on the first pass.'],
    ['title' => 'Design & Refinement', 'copy' => 'We build the approved concept into polished, production-ready designs, with your feedback incorporated at each stage until the work is exactly right.'],
    ['title' => 'Revision Rounds', 'copy' => 'We refine based on your structured feedback through the agreed number of revision rounds, keeping the process moving without the open-ended back-and-forth that delays most design projects.'],
    ['title' => 'Final Delivery', 'copy' => 'We deliver all source files and export formats your team needs, organized, labeled, and ready to hand to a printer, upload to social media, or pass to any other team without additional preparation.'],
  ],
  'faqHeading' => 'Graphic Design Questions',
  'faqHeadingMuted' => 'From UAE Business Owners.',
  'faqs' => [
    ['question' => 'What file formats will I receive when the design is finished?', 'answer' => 'You receive the complete set of source files in their original working format, typically Adobe Illustrator or Photoshop for print work and Figma for digital assets, alongside export-ready versions in PNG, JPG, and PDF at the correct resolutions for both screen and print use. Every file is organized and labeled at handover so your team can find and use what they need without having to come back to us for a basic resize or export.'],
    ['question' => 'How many revision rounds are included?', 'answer' => 'Revision rounds are confirmed in your project proposal before work begins, so there are no surprises. Most graphic design projects include two to three structured revision rounds, which is sufficient to reach a final result your team is genuinely happy with when feedback is specific and consolidated at each stage rather than drip-fed over many rounds.'],
    ['question' => 'Can you redesign or refresh our existing brand visuals instead of starting from scratch?', 'answer' => 'Yes. We work with existing brand assets regularly, whether that means refining a logo that is close but not quite right, building a consistent template system around colours your business already uses, or updating collateral to reflect a rebrand. We assess what currently exists before recommending whether a refresh or a full redesign is the more practical approach for your specific situation and budget.'],
    ['question' => 'Do you design in Arabic as well as English?', 'answer' => 'Yes. We design bilingual materials with proper Arabic typography, correct right-to-left layout handling, and font selection that works in Arabic, not just mirrored English layouts with Arabic text dropped in. For UAE businesses targeting Arabic and English-speaking audiences, properly executed bilingual design makes a significant difference in how your brand is perceived across both communities.'],
    ['question' => 'How much does graphic designing cost in Dubai?', 'answer' => 'Graphic design pricing in Dubai depends on the scope, number of deliverables, and complexity of the brief. A logo design project is priced differently from an ongoing monthly social media graphics retainer or a full marketing collateral package. Most graphic design companies in the UAE, including Optimizers, provide a fixed-price proposal based on your specific requirements after an initial consultation, so the full cost is clear and agreed before any design work begins.'],
  ],
  'related' => [
    ['title' => 'Business Branding & Designing', 'url' => 'business-branding-designing.php'],
    ['title' => 'Content Creation & Reels', 'url' => 'content-creation-reels.php'],
    ['title' => 'Video Editing', 'url' => 'video-editing.php'],
    ['title' => 'Social Media Marketing', 'url' => 'index.php#social-media-marketing'],
  ],
  'ctaHeading' => 'Ready to Make Your UAE Business',
  'ctaHeadingMuted' => 'Look Its Best?',
  'ctaCopy' => 'Get a free design consultation and we will show you exactly how we would approach your brand’s visual identity and design requirements.',
];

require __DIR__ . '/service-page-template.php';
