<?php
$servicePage = [
  'slug' => 'international-seo',
  'pageTitle' => 'International SEO Services in Dubai | UAE | Optimizers',
  'pageDescription' => 'International SEO services for UAE businesses expanding into GCC and global markets.',
  'categoryLabel' => 'SEO',
  'heroIcon' => 'assets/icons/brand/google.svg',
  'heroArtwork' => 'assets/images/service-pages/optimizers-global-reach-map.svg',
  'heroArtworkAlt' => 'Global reach map preview',
  'heroEyebrow' => 'INTERNATIONAL SEO SERVICES',
  'heroHeading' => 'International SEO Services That Help UAE Businesses Reach the Right Markets',
  'heroHeadingMuted' => '',
  'heroDescription' => 'Expanding your UAE business into Saudi Arabia, other GCC countries, or international markets requires more than translating your content. We structure your website so search engines understand which version of each page to show to which country, implementing hreflang, geotargeting, and country-specific keyword strategies.',
  'auditLabel' => 'Get a Free International SEO Audit',
  'heroMeta' => ['UAE · SAUDI ARABIA · GCC · INTERNATIONAL', 'HREFLANG · MULTI-REGION · LOCAL SEARCH'],
  'overviewEyebrow' => 'WHAT IS INTERNATIONAL SEO',
  'overviewHeading' => 'International SEO,',
  'overviewHeadingMuted' => 'Explained Simply.',
  'overviewCopy' => 'International SEO is the practice of structuring a website so search engines understand which version of a page should be shown to which country or region, primarily through hreflang tags, careful URL structure decisions, and geotargeting settings. It prevents near-identical regional pages from competing against each other and helps the correct country version appear for the correct audience.',
  'stats' => [['value'=>'200+', 'label'=>'UAE Clients'], ['value'=>'5.0', 'label'=>'Google Rating']],
  'includedHeading' => 'What Our International SEO Service',
  'includedHeadingMuted' => 'Covers.',
  'includedCopy' => 'Every page we touch goes through the same complete checklist, not a partial pass.',
  'included' => [['title'=>'Hreflang Implementation', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'ccTLD vs Subdirectory vs Subdomain Strategy', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Country-Specific Keyword Research', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'International Duplicate Content Management', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Geotargeting Setup in Search Console', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Local Currency & Regional Signal Adaptation', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'International Site Architecture Planning', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Cross-Region Internal Linking Strategy', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>'']],
  'whyHeading' => 'Why International SEO Matters',
  'whyHeadingMuted' => 'for Your UAE Business.',
  'why' => [['title'=>'Opens New Markets Without Starting Over', 'copy'=>'Properly structured international SEO lets you expand into Saudi Arabia or other GCC markets while keeping the UAE rankings you’ve already built.'], ['title'=>'Prevents Regional Pages From Competing With Each Other', 'copy'=>'Correct hreflang and canonical setup helps country pages rank for their own markets instead of competing with each other.'], ['title'=>'Matches Content to the Right Audience Automatically', 'copy'=>'Search engines and browsers can serve the correct regional page without the visitor needing to manually pick a country.'], ['title'=>'Builds a Foundation for Multilingual Growth', 'copy'=>'A properly structured international setup makes it easier to layer in Arabic or other language content later.']],
  'processHeading' => 'How We Approach International SEO',
  'processHeadingMuted' => 'for UAE Businesses.',
  'process' => [['title'=>'Market & Site Audit', 'copy'=>'We review your current site structure and identify which countries or regions are realistic expansion targets.'], ['title'=>'URL Structure Strategy', 'copy'=>'We recommend whether subdirectories, subdomains, or separate domains fit your goals and resources best.'], ['title'=>'Hreflang & Geotargeting Setup', 'copy'=>'We implement hreflang tags and Search Console geotargeting so each page reaches the right audience.'], ['title'=>'Regional Content Mapping', 'copy'=>'We plan which content needs region-specific versions versus what can stay shared across markets.'], ['title'=>'Monitoring & Expansion', 'copy'=>'We track regional ranking performance and help plan the next market as your business grows.']],
  'faqHeading' => 'International SEO Questions',
  'faqHeadingMuted' => 'From UAE Business Owners.',
  'faqs' => [['question'=>'What is the difference between international SEO and multilingual SEO?', 'answer'=>'International SEO structures your site so the right country or region sees the right version through hreflang, URL structure, and geotargeting. Multilingual SEO handles the actual content creation in different languages.'], ['question'=>'Should I use a ccTLD, subdirectory, or subdomain for targeting other countries?', 'answer'=>'It depends on your resources. A ccTLD gives a strong country-specific signal but requires building authority from scratch. A subdirectory shares existing domain authority and is often more practical for UAE businesses expanding into nearby GCC markets.'], ['question'=>'What is hreflang and why does it matter?', 'answer'=>'Hreflang is code that tells search engines which language or country version of a page to show a specific user. It helps prevent the wrong regional page appearing or regional pages competing as duplicates.'], ['question'=>'Will targeting multiple countries hurt my existing UAE rankings?', 'answer'=>'No, when implemented correctly. Proper hreflang and geotargeting tell search engines which page serves which market.'], ['question'=>'Does my business need international SEO if I only sell within the UAE?', 'answer'=>'Probably not yet. International SEO becomes relevant once you actively target customers in Saudi Arabia, other GCC countries, or markets beyond the region.'], ['question'=>'How much does international SEO cost?', 'answer'=>'International SEO services typically start from AED 3,000 to AED 5,000 per month depending on how many countries or regions are being targeted.']],
  'related' => [['title'=>'Off Page SEO', 'url'=>'off-page-seo.php'], ['title'=>'On Page SEO', 'url'=>'on-page-seo.php'], ['title'=>'AI SEO', 'url'=>'ai-seo-services-aeo-geo-llm-seo.php'], ['title'=>'International SEO', 'url'=>'international-seo.php'], ['title'=>'Local SEO', 'url'=>'local-seo-service.php'], ['title'=>'E-Commerce SEO', 'url'=>'e-commerce-seo-services.php'], ['title'=>'Technical SEO', 'url'=>'technical-seo.php']],
  'ctaHeading' => 'Ready to Expand Beyond the UAE?',
  'ctaHeadingMuted' => '',
  'ctaCopy' => 'Get a free international SEO audit showing exactly what’s needed to target new markets without risking your current rankings.',
];
require __DIR__ . '/service-page-template.php';