<?php
$servicePage = [
  'slug' => 'keyword-research',
  'pageTitle' => 'Keyword Research Services in Dubai | UAE | Optimizers',
  'pageDescription' => 'Keyword research services built on real UAE search demand and intent.',
  'categoryLabel' => 'SEO',
  'heroIcon' => 'assets/icons/brand/google.svg',
  'heroArtwork' => 'assets/images/service-pages/optimizers-keyword-opportunity-finder.svg',
  'heroArtworkAlt' => 'Keyword opportunity finder preview',
  'heroEyebrow' => 'KEYWORD RESEARCH SERVICES',
  'heroHeading' => 'Keyword Research Services Built on Real UAE Search Demand',
  'heroHeadingMuted' => '',
  'heroDescription' => 'Every page on a website should be built around a real, specific search someone is actually making, not a guess. We research the exact terms, semantic variations, and related concepts UAE customers search for, then map every keyword to the right page before a single word gets written.',
  'auditLabel' => 'Get a Free Keyword Research Audit',
  'heroMeta' => ['SEARCH INTENT · LOW COMPETITION · HIGH VOLUME', 'KEYWORD-TO-PAGE MAPPING'],
  'overviewEyebrow' => 'WHAT IS KEYWORD RESEARCH',
  'overviewHeading' => 'Keyword Research,',
  'overviewHeadingMuted' => 'Explained Simply.',
  'overviewCopy' => 'Keyword research is the process of identifying which terms, questions, and related concepts people actually search for around a topic, then deciding which ones a business should target and on which page. It goes beyond a single exact phrase to include semantic and LSI keywords and NLP-derived entities. Good keyword research is the foundation every other piece of content and SEO work gets built on top of.',
  'stats' => [['value'=>'200+', 'label'=>'UAE Clients'], ['value'=>'5.0', 'label'=>'Google Rating']],
  'includedHeading' => 'What Our Keyword Research Service',
  'includedHeadingMuted' => 'Covers.',
  'includedCopy' => 'Every page we touch goes through the same complete checklist, not a partial pass.',
  'included' => [['title'=>'Search Intent Mapping', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Competitor Keyword Gap Analysis', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Semantic & LSI Keyword Identification', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'NLP Entity Research', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Long-Tail Keyword Discovery', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Question-Based Keyword Research', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Keyword-to-Page Mapping', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Search Volume & Difficulty Analysis', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>'']],
  'whyHeading' => 'Why Keyword Research Matters',
  'whyHeadingMuted' => 'for Your UAE Business.',
  'why' => [['title'=>'Every Page Targets Real Demand', 'copy'=>'Content built on actual search data performs fundamentally differently than content built on assumptions about what people search.'], ['title'=>'Prevents Pages From Competing With Each Other', 'copy'=>'Proper keyword-to-page mapping stops two pages from splitting ranking potential by accidentally targeting the same term.'], ['title'=>'Captures More Than One Keyword Ever Could', 'copy'=>'Semantic and LSI research means a page can rank for related searches, not just one exact phrase.'], ['title'=>'Removes the Guesswork From Content Planning', 'copy'=>'Every piece of content has a clear, data-backed reason to exist.']],
  'processHeading' => 'How We Approach Keyword Research',
  'processHeadingMuted' => 'for UAE Businesses.',
  'process' => [['title'=>'Seed Keyword & Topic Discovery', 'copy'=>'We identify the core topics and terms most relevant to your business and UAE audience.'], ['title'=>'Competitor Gap Analysis', 'copy'=>'We map what competitors rank for that you currently don’t, surfacing real opportunities.'], ['title'=>'Semantic & LSI Expansion', 'copy'=>'We expand each core keyword into related semantic and NLP entity terms.'], ['title'=>'Intent Classification & Clustering', 'copy'=>'We group keywords by search intent and topic, so related terms get assigned together.'], ['title'=>'Mapping & Reporting', 'copy'=>'We assign every keyword to one primary page and hand off a clear roadmap for content and SEO teams to execute.']],
  'faqHeading' => 'Keyword Research Questions',
  'faqHeadingMuted' => 'From UAE Business Owners.',
  'faqs' => [['question'=>'What are LSI keywords and why do they matter?', 'answer'=>'LSI stands for Latent Semantic Indexing, an older term still used to describe keywords conceptually related to your main topic. Including naturally related terms helps search engines understand the full context of a page.'], ['question'=>'What is the difference between keyword research and semantic SEO content writing?', 'answer'=>'Keyword research is the discovery phase, identifying which terms and topics to target. Semantic content writing is the execution phase, using that research to write content built around real search intent and topical depth.'], ['question'=>'What are NLP keywords in SEO?', 'answer'=>'NLP, or Natural Language Processing, is the technology search engines use to understand the meaning and relationships between words. NLP keyword research looks at entities and concepts search engines extract from top-ranking content.'], ['question'=>'How do you avoid keyword cannibalization across pages?', 'answer'=>'We map every keyword to exactly one primary page before content gets written, so no two pages on your site compete against each other.'], ['question'=>'How many keywords should I target per page?', 'answer'=>'There’s no fixed number. Most pages should have one primary keyword and a handful of closely related semantic and long-tail variations woven in naturally.'], ['question'=>'How much does keyword research cost in the UAE?', 'answer'=>'Keyword research services typically start from AED 1,500 to AED 3,000 for an initial research and mapping project, depending on site size and pages covered.']],
  'related' => [['title'=>'Off Page SEO', 'url'=>'off-page-seo.php'], ['title'=>'On Page SEO', 'url'=>'on-page-seo.php'], ['title'=>'AI SEO', 'url'=>'ai-seo-services-aeo-geo-llm-seo.php'], ['title'=>'International SEO', 'url'=>'international-seo.php'], ['title'=>'Local SEO', 'url'=>'local-seo-service.php'], ['title'=>'E-Commerce SEO', 'url'=>'e-commerce-seo-services.php'], ['title'=>'Technical SEO', 'url'=>'technical-seo.php']],
  'ctaHeading' => 'Ready to Stop Guessing What to Write?',
  'ctaHeadingMuted' => '',
  'ctaCopy' => 'Get a free keyword gap analysis showing exactly what your UAE competitors are ranking for that you’re not.',
];
require __DIR__ . '/service-page-template.php';