<?php
$servicePage = [
  'slug' => 'local-seo-service',
  'pageTitle' => 'Local SEO Services in Dubai | UAE | Optimizers',
  'pageDescription' => 'Local SEO services that help UAE businesses get found on Google Maps and local search.',
  'categoryLabel' => 'SEO',
  'heroIcon' => 'assets/icons/brand/google.svg',
  'heroArtwork' => 'assets/images/service-pages/optimizers-local-search-pack.svg',
  'heroArtworkAlt' => 'Local search pack preview',
  'heroEyebrow' => 'LOCAL SEO SERVICES',
  'heroHeading' => 'Local SEO Services That Get Your UAE Business Found on Google Maps',
  'heroHeadingMuted' => '',
  'heroDescription' => 'We optimize your Google Business Profile, local citations, and Google Maps presence so customers searching nearby in Dubai and across the UAE find your business first, not just your website, but the map pack, “near me” results, and GPS-driven searches that lead straight to your door.',
  'auditLabel' => 'Get a Free Local SEO Audit',
  'heroMeta' => ['GOOGLE BUSINESS PROFILE · MAPS · REVIEWS', 'GMB OPTIMIZATION · LOCAL SEARCH'],
  'overviewEyebrow' => 'WHAT IS LOCAL SEO',
  'overviewHeading' => 'Local SEO,',
  'overviewHeadingMuted' => 'Explained Simply.',
  'overviewCopy' => 'Local SEO is the practice of optimizing your online presence so your business appears when people search for products or services near their current location, whether they type “near me” or are guided purely by GPS through Google Maps. It centers on your Google Business Profile, consistent local citations, and proximity and relevance signals that determine who shows up in the map pack.',
  'stats' => [['value'=>'200+', 'label'=>'UAE Clients'], ['value'=>'5.0', 'label'=>'Google Rating']],
  'includedHeading' => 'What Our Local SEO Service',
  'includedHeadingMuted' => 'Covers.',
  'includedCopy' => 'Every page we touch goes through the same complete checklist, not a partial pass.',
  'included' => [['title'=>'Google Business Profile Optimization', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Google Maps & GPS Visibility Optimization', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Local Citations & NAP Consistency', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Map Pack Ranking Strategy', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Review Generation & Management', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Near Me & Location-Based Keyword Targeting', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Local Schema Markup', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Multi-Location Management', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>'']],
  'whyHeading' => 'Why Local SEO Matters',
  'whyHeadingMuted' => 'for Your UAE Business.',
  'why' => [['title'=>'Captures the Highest-Intent Searches', 'copy'=>'Someone searching “near me” or following GPS directions is often minutes away from visiting or calling, making local visibility highly valuable.'], ['title'=>'The Map Pack Gets Seen Before Organic Results', 'copy'=>'On mobile, the map pack can appear above traditional organic results, making it valuable search real estate.'], ['title'=>'Builds Trust Through Reviews', 'copy'=>'A strong review profile helps rankings and is often the deciding factor for a customer choosing between nearby competitors.'], ['title'=>'Works for Single and Multi-Location Businesses', 'copy'=>'Whether you have one location in Dubai or branches across several emirates, local SEO can scale by location.']],
  'processHeading' => 'How We Approach Local SEO',
  'processHeadingMuted' => 'for UAE Businesses.',
  'process' => [['title'=>'Profile & Citation Audit', 'copy'=>'We review your current Google Business Profile and citation accuracy across major UAE directories.'], ['title'=>'Optimization & Cleanup', 'copy'=>'We fully optimize your profile and correct inconsistent NAP data wherever it appears.'], ['title'=>'Review & Engagement Strategy', 'copy'=>'We set up a system for generating and responding to genuine customer reviews.'], ['title'=>'Map Pack Targeting', 'copy'=>'We optimize for specific local keywords and categories most likely to earn map pack visibility.'], ['title'=>'Tracking & Reporting', 'copy'=>'We track local ranking position, map views, and direction requests monthly.']],
  'faqHeading' => 'Local SEO Questions',
  'faqHeadingMuted' => 'From UAE Business Owners.',
  'faqs' => [['question'=>'What is the difference between local SEO and regular SEO?', 'answer'=>'Regular SEO focuses on ranking your website in general search results. Local SEO focuses specifically on location-based results, the map pack, “near me” searches, and Google Maps navigation.'], ['question'=>'How important is Google Maps optimization for a UAE business?', 'answer'=>'Extremely important if you have a physical location or serve a specific area. Map visibility can be one of the most direct paths to a walk-in customer.'], ['question'=>'How many Google reviews do I need to rank well locally?', 'answer'=>'There is no fixed number, but review count, rating, and recency all factor into local visibility. Consistently generating genuine reviews matters more than chasing one large batch.'], ['question'=>'Can local SEO help if I serve customers across multiple emirates?', 'answer'=>'Yes. We can optimize a single service-area profile or manage multiple location-specific profiles depending on your physical branches and service model.'], ['question'=>'How long does it take to rank in the local map pack?', 'answer'=>'Many UAE businesses see initial improvement within 4 to 8 weeks for citation and profile fixes, with stronger rankings building over 3 to 6 months.'], ['question'=>'How much does local SEO cost in the UAE?', 'answer'=>'Local SEO services typically start from AED 1,500 to AED 2,500 per month for a single location, with multi-location pricing scaling by branches managed.']],
  'related' => [['title'=>'Off Page SEO', 'url'=>'off-page-seo.php'], ['title'=>'On Page SEO', 'url'=>'on-page-seo.php'], ['title'=>'AI SEO', 'url'=>'ai-seo-services-aeo-geo-llm-seo.php'], ['title'=>'International SEO', 'url'=>'international-seo.php'], ['title'=>'Local SEO', 'url'=>'local-seo-service.php'], ['title'=>'E-Commerce SEO', 'url'=>'e-commerce-seo-services.php'], ['title'=>'Technical SEO', 'url'=>'technical-seo.php']],
  'ctaHeading' => 'Ready to Show Up When Customers Search Nearby?',
  'ctaHeadingMuted' => '',
  'ctaCopy' => 'Get a free local SEO audit showing exactly how your Google Business Profile and map visibility compare to nearby competitors.',
];
require __DIR__ . '/service-page-template.php';