<?php
$servicePage = [
  'slug' => 'off-page-seo',
  'pageTitle' => 'Off-Page SEO Services in Dubai | UAE | Optimizers',
  'pageDescription' => 'Off-Page SEO services that build real authority for UAE websites.',
  'categoryLabel' => 'SEO',
  'heroIcon' => 'assets/icons/brand/google.svg',
  'heroArtwork' => 'assets/images/service-pages/optimizers-backlink-authority-network-material-link.svg',
  'heroArtworkAlt' => 'Backlink authority network preview',
  'heroEyebrow' => 'OFF-PAGE SEO SERVICES',
  'heroHeading' => 'Off-Page SEO Services That Build Real Authority for Your UAE Website',
  'heroHeadingMuted' => '',
  'heroDescription' => 'Google doesn’t just look at your website, it looks at how the rest of the internet talks about it. We build genuine backlinks, brand mentions, and digital PR that strengthen how search engines and AI tools view your UAE business, without resorting to spammy link schemes.',
  'auditLabel' => 'Get a Free Off Page SEO Audit',
  'heroMeta' => ['BACKLINKS · DIGITAL PR · BRAND MENTIONS', 'DA 45+ · 120+ QUALITY BACKLINKS · WHITE-HAT'],
  'overviewEyebrow' => 'WHAT IS OFF-PAGE SEO',
  'overviewHeading' => 'Off-Page SEO,',
  'overviewHeadingMuted' => 'Explained Simply.',
  'overviewCopy' => 'Off-page SEO is the work that happens outside your own website to build its authority and reputation in the eyes of search engines, primarily through backlinks from other reputable sites, but also through brand mentions, digital PR, and social signals. Where on-page SEO optimizes your content and technical SEO fixes your infrastructure, off-page SEO builds the trust signals that come from the rest of the internet vouching for your business.',
  'stats' => [['value'=>'200+', 'label'=>'UAE Clients'], ['value'=>'5.0', 'label'=>'Google Rating']],
  'includedHeading' => 'What Our Off-Page SEO Service',
  'includedHeadingMuted' => 'Covers.',
  'includedCopy' => 'Every page we touch goes through the same complete checklist, not a partial pass.',
  'included' => [['title'=>'Backlink Strategy & Outreach', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Guest Posting & Content Placement', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Digital PR & Brand Mentions', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Competitor Backlink Gap Analysis', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Toxic Link Audit & Disavow', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Social Signal Building', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>'']],
  'whyHeading' => 'Why Off-Page SEO Matters',
  'whyHeadingMuted' => 'for Your UAE Business.',
  'why' => [['title'=>'Builds Trust Search Engines Can\'t Fake', 'copy'=>'A backlink from a reputable site acts as a vote of confidence that’s much harder to manipulate than on-page tactics alone.'], ['title'=>'Helps You Outrank Bigger Competitors', 'copy'=>'Strong off-page authority is often what separates two sites with similar on-page quality, letting a smaller UAE business compete with bigger names.'], ['title'=>'Compounds Over Time', 'copy'=>'Unlike paid ads, the authority built through quality backlinks keeps working in your favor long after the outreach work is done.'], ['title'=>'Strengthens Brand Visibility Beyond Search', 'copy'=>'Digital PR and mentions build awareness with real people, not just search engine crawlers, creating demand that shows up in branded searches too.']],
  'processHeading' => 'How We Approach Off-Page SEO',
  'processHeadingMuted' => 'for UAE Businesses.',
  'process' => [['title'=>'Backlink Audit', 'copy'=>'We review your current backlink profile and identify both opportunities and toxic links to clean up.'], ['title'=>'Competitor Gap Analysis', 'copy'=>'We map where competitors are earning links that you currently aren’t.'], ['title'=>'Outreach & Placement', 'copy'=>'We pitch and place content on relevant, reputable sites that strengthen your domain authority.'], ['title'=>'Digital PR Campaigns', 'copy'=>'We pursue press and mention opportunities that build brand visibility alongside SEO value.'], ['title'=>'Monitoring & Reporting', 'copy'=>'We track new backlinks, lost links, and overall domain authority growth monthly.']],
  'faqHeading' => 'Off-Page SEO Questions',
  'faqHeadingMuted' => 'From UAE Business Owners.',
  'faqs' => [['question'=>'How is off-page SEO different from on-page or technical SEO?', 'answer'=>'On-page SEO optimizes your content, technical SEO fixes your site’s infrastructure, and off-page SEO builds authority from outside your website, primarily through backlinks and digital PR.'], ['question'=>'Are backlinks still important for SEO in 2026?', 'answer'=>'Yes. Backlinks from relevant, reputable sites remain an important trust signal and can also support how AI systems assess credible sources.'], ['question'=>'Can buying backlinks get my site penalized?', 'answer'=>'Yes, purchased or low-quality links from spammy networks can trigger a Google penalty. We focus on earned and outreach-based links from genuinely relevant, reputable sources.'], ['question'=>'How long does it take to see results from off-page SEO?', 'answer'=>'Authority growth depends on outreach volume, competitiveness, and the quality of placements. It normally compounds over time rather than appearing immediately.'], ['question'=>'How much does off-page SEO cost in the UAE?', 'answer'=>'Off-page SEO services in the UAE typically start from AED 2,500 to AED 4,000 per month depending on outreach volume and competitiveness.']],
  'related' => [['title'=>'Off Page SEO', 'url'=>'off-page-seo.php'], ['title'=>'On Page SEO', 'url'=>'on-page-seo.php'], ['title'=>'AI SEO', 'url'=>'ai-seo-services-aeo-geo-llm-seo.php'], ['title'=>'International SEO', 'url'=>'international-seo.php'], ['title'=>'Local SEO', 'url'=>'local-seo-service.php'], ['title'=>'E-Commerce SEO', 'url'=>'e-commerce-seo-services.php'], ['title'=>'Technical SEO', 'url'=>'technical-seo.php']],
  'ctaHeading' => 'Ready to Build Real Authority for Your Website?',
  'ctaHeadingMuted' => '',
  'ctaCopy' => 'Get a free backlink audit showing exactly where your authority stands against your UAE competitors.',
];
require __DIR__ . '/service-page-template.php';