<?php
$servicePage = [
  'slug' => 'on-page-seo',
  'pageTitle' => 'On-Page SEO Services in Dubai | UAE | Optimizers',
  'pageDescription' => 'On-Page SEO services that help UAE pages rank for the right keywords.',
  'categoryLabel' => 'SEO',
  'heroIcon' => 'assets/icons/brand/google.svg',
  'heroArtwork' => 'assets/images/service-pages/optimizers-seo-on-page-score.svg',
  'heroArtworkAlt' => 'On-page SEO score preview',
  'heroEyebrow' => 'ON-PAGE SEO SERVICES',
  'heroHeading' => 'On-Page SEO Services That Help UAE Pages Rank for the Right Keywords',
  'heroHeadingMuted' => '',
  'heroDescription' => 'We optimize titles, headers, content, and internal links on every page so search engines understand exactly what it’s about, and rank it for the terms that actually bring buyers.',
  'auditLabel' => 'Get a Free On Page SEO Audit',
  'heroMeta' => ['TITLE · HEADERS · CONTENT · INTERNAL LINKS', '92 / 100 ON-PAGE SCORE'],
  'overviewEyebrow' => 'WHAT IS ON-PAGE SEO?',
  'overviewHeading' => 'On-Page SEO,',
  'overviewHeadingMuted' => 'Explained Simply.',
  'overviewCopy' => 'On-page SEO is the practice of optimizing the content and structure of an individual web page, its title tag, headings, body content, internal links, images, and schema markup, so search engines understand what the page is about and rank it for the right search terms. Unlike technical SEO, which deals with the whole site, on-page SEO works page by page, and it is the foundation every other SEO effort builds on top of.',
  'stats' => [['value'=>'200+', 'label'=>'UAE Clients'], ['value'=>'5.0', 'label'=>'Google Rating']],
  'includedHeading' => 'What Our On-Page SEO Service',
  'includedHeadingMuted' => 'Covers.',
  'includedCopy' => 'Every page we touch goes through the same complete checklist, not a partial pass.',
  'included' => [['title'=>'Title Tag & Meta Description Optimization', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Image Alt Text & Compression', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Header Tag Structure (H1 to H6)', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'URL Structure & Slug Optimization', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Keyword Placement & Content Optimization', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Schema Markup Implementation', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Internal Linking Strategy', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>''], ['title'=>'Core Web Vitals & Mobile Usability Check', 'icon'=>'assets/icons/brand/google.svg', 'copy'=>'']],
  'whyHeading' => 'Why On-Page SEO Matters',
  'whyHeadingMuted' => 'for Your UAE Business.',
  'why' => [['title'=>'Higher Click-Through Rates', 'copy'=>'Optimized titles and meta descriptions make your listing more clickable in search results.'], ['title'=>'Stronger Keyword Relevance', 'copy'=>'Properly structured content tells Google exactly what your page is about.'], ['title'=>'Better User Experience', 'copy'=>'Clear headings and clean structure keep visitors on your page instead of bouncing back to Google.'], ['title'=>'A Stronger Foundation', 'copy'=>'Off-page SEO and paid campaigns perform better when the page they point to is already optimized.']],
  'processHeading' => 'How We Approach On-Page SEO',
  'processHeadingMuted' => 'for UAE Businesses.',
  'process' => [['title'=>'Page Audit', 'copy'=>'We review current pages against on-page best practices.'], ['title'=>'Keyword Mapping', 'copy'=>'We assign target keywords to the right pages.'], ['title'=>'Implementation', 'copy'=>'We optimize titles, headers, content, and schema markup.'], ['title'=>'Quality Review', 'copy'=>'We check every change against UAE search intent.'], ['title'=>'Reporting', 'copy'=>'We track ranking and traffic changes monthly.']],
  'faqHeading' => 'On-Page SEO Questions',
  'faqHeadingMuted' => 'From UAE Business Owners.',
  'faqs' => [['question'=>'How much does digital marketing cost in Dubai and the UAE?', 'answer'=>'Digital marketing costs in the UAE typically range from AED 3,000 to AED 30,000 per month depending on the services required, the number of channels, and the size of the business. SEO retainers generally start from AED 3,500 per month. Google Ads management starts from AED 2,000 per month, separate from ad spend budget. At Optimizers, we build custom proposals after understanding your specific situation.'], ['question'=>'How long does SEO take to show results in the UAE?', 'answer'=>'In the UAE market, most businesses see measurable SEO improvements within 3 to 4 months for local and medium-competition keywords. Highly competitive terms typically require 6 to 12 months of consistent SEO work.'], ['question'=>'Which digital marketing channel works best for UAE businesses?', 'answer'=>'The right channel depends entirely on your business type, goals, and where your buyers spend their time. Google Ads produces immediate results for high-intent searches, SEO builds long-term organic traffic, WhatsApp marketing achieves very high open rates, and Instagram and TikTok work well for visual consumer brands. Most UAE businesses that grow consistently use at least two channels working together.'], ['question'=>'Do Optimizers work with businesses outside of Dubai?', 'answer'=>'Yes. We serve businesses across all seven UAE emirates and also support UAE businesses targeting GCC and international markets.'], ['question'=>'What makes Optimizers different from other digital marketing agencies in the UAE?', 'answer'=>'We combine strategy, execution, UAE market data, and clear consulting rather than treating digital marketing as a black-box vendor service.'], ['question'=>'Can Optimizers manage both SEO and Google Ads at the same time?', 'answer'=>'Yes. Google Ads provides immediate visibility while SEO builds organic authority over time, and the two channels can be coordinated under one growth strategy.'], ['question'=>'Do you offer digital marketing services in Arabic?', 'answer'=>'Yes. Campaigns, copy, and SEO content can be produced in both Arabic and English for UAE and wider Gulf audiences.'], ['question'=>'How do I get started with Optimizers?', 'answer'=>'The first step is a free strategy call. We review your current digital presence, identify the biggest opportunities, and explain what we would do without requiring a commitment.']],
  'related' => [['title'=>'Off Page SEO', 'url'=>'off-page-seo.php'], ['title'=>'On Page SEO', 'url'=>'on-page-seo.php'], ['title'=>'AI SEO', 'url'=>'ai-seo-services-aeo-geo-llm-seo.php'], ['title'=>'International SEO', 'url'=>'international-seo.php'], ['title'=>'Local SEO', 'url'=>'local-seo-service.php'], ['title'=>'E-Commerce SEO', 'url'=>'e-commerce-seo-services.php'], ['title'=>'Technical SEO', 'url'=>'technical-seo.php']],
  'ctaHeading' => 'Ready to Fix Your On-Page SEO?',
  'ctaHeadingMuted' => '',
  'ctaCopy' => 'Get a free audit showing exactly what’s holding your pages back, and what it would take to fix it.',
];
require __DIR__ . '/service-page-template.php';