<?php
$servicePage = [
  'slug' => 'shopify-development',
  'pageTitle' => 'Shopify Development Company Dubai | UAE | Optimizers',
  'pageDescription' => 'Shopify development services in Dubai for UAE e-commerce businesses, including custom themes, payment gateways, apps, migration, Shopify Plus, SEO, and store launch support.',
  'heroIcon' => 'assets/icons/service-pages/shopify.svg',
  'heroEyebrow' => 'Shopify Development Services',
  'heroHeading' => 'Shopify Development in Dubai',
  'heroHeadingMuted' => 'for UAE E-Commerce Businesses That Want to Sell and Scale',
  'heroDescription' => 'We build, customize, and optimize Shopify stores for UAE businesses ready to launch or grow their e-commerce. As a certified Shopify development company in Dubai delivering Shopify development services in Dubai across all seven emirates, we handle everything from custom Shopify theme development and UAE payment gateway integration to Shopify Plus configuration and custom app development, so your store is built to convert from day one.',
  'auditLabel' => 'Get a Shopify Development Free Audit',
  'heroMeta' => ['YOURSTORE.AE · SHOPIFY · E-COMMERCE', 'SECURE CHECKOUT · MOBILE READY'],
  'overviewEyebrow' => 'What Is Shopify Development',
  'overviewHeading' => 'Shopify Development,',
  'overviewHeadingMuted' => 'Explained Simply.',
  'overviewCopy' => 'Shopify development is the process of building, customizing, and configuring an online store on the Shopify platform, covering everything from custom Shopify theme development and product catalog structure to UAE payment gateway integration and app configuration. Unlike a fully custom-built e-commerce site, Shopify is a hosted platform with no server infrastructure to manage, so your store stays live, fast, and secure without any technical maintenance burden on your team. Done properly, a Shopify ecommerce website development project gives you a professional, UAE-ready store that your team can manage independently long after launch.',
  'stats' => [
    ['value' => '200+', 'label' => 'UAE Clients'],
    ['value' => '5.0', 'label' => 'Google Rating'],
  ],
  'includedHeading' => 'What Our Shopify Development',
  'includedHeadingMuted' => 'Service Covers.',
  'includedCopy' => 'Every Shopify store build goes through the same complete process, not a stripped-down version to hit a lower price.',
  'included' => [
    ['title' => 'Custom Shopify Theme Development', 'icon' => 'assets/icons/service-pages/shopify.svg'],
    ['title' => 'UAE Payment Gateway Integration', 'icon' => 'assets/icons/service-pages/support.svg'],
    ['title' => 'Product Catalog Setup & Import', 'icon' => 'assets/icons/service-pages/shopify.svg'],
    ['title' => 'Shopify App Development & Integration', 'icon' => 'assets/icons/service-pages/code.svg'],
    ['title' => 'Mobile-First Responsive Design', 'icon' => 'assets/icons/service-pages/mobile.svg'],
    ['title' => 'Shopify Plus Development', 'icon' => 'assets/icons/service-pages/shopify.svg'],
    ['title' => 'Speed, SEO & Analytics Setup', 'icon' => 'assets/icons/service-pages/support.svg'],
    ['title' => 'Store Training & Handover Documentation', 'icon' => 'assets/icons/service-pages/support.svg'],
  ],
  'whyHeading' => 'Why Shopify Is the Right Platform',
  'whyHeadingMuted' => 'for UAE E-Commerce.',
  'why' => [
    ['title' => 'Faster to Market Than Any Alternative', 'copy' => 'A properly scoped Shopify store goes from approved brief to live in 4 to 6 weeks, significantly faster than a custom e-commerce build without sacrificing conversion quality or feature depth.'],
    ['title' => 'Built for How UAE Customers Pay and Browse', 'copy' => 'Shopify supports UAE payment gateways, Arabic RTL layouts, and local shipping carrier integrations natively, removing the most common friction points for UAE online stores before the first order arrives.'],
    ['title' => 'Scales Directly to Shopify Plus', 'copy' => 'Start on a standard Shopify plan and upgrade to Shopify Plus when enterprise features like custom checkout scripting, wholesale channels, or automation workflows are needed, without rebuilding the store from scratch.'],
    ['title' => 'Marketing-Ready From Launch Day', 'copy' => 'Every store we build has tracking, URL structure, and conversion setup ready to run Google Shopping campaigns and Meta product catalog ads the moment the store goes live, with no additional setup required.'],
  ],
  'processHeading' => 'How We Build',
  'processHeadingMuted' => 'Your Shopify Store.',
  'process' => [
    ['title' => 'Discovery & Store Planning', 'copy' => 'We map your products, audience, UAE payment preferences, shipping requirements, and brand identity before touching the platform, producing a documented store blueprint that prevents scope creep.'],
    ['title' => 'Design & Custom Theme Development', 'copy' => 'We design every page layout for approval before development begins. Custom Shopify theme builds cover every section, template, and interactive element built to Shopify’s latest theme standards.'],
    ['title' => 'App Integration & Store Configuration', 'copy' => 'We integrate every required app and configure the complete store, UAE payment gateways, shipping zones, VAT tax rules, navigation, collections, and product pages, so the back-end is as organized as the storefront.'],
    ['title' => 'Testing, Speed & SEO', 'copy' => 'We test every page, checkout flow, and payment method across all devices before launch. Core Web Vitals checks, image optimization, and SEO foundation setup complete the pre-launch checklist.'],
    ['title' => 'Launch, Training & Support', 'copy' => 'We launch the store and complete a recorded training handover. Post-launch support is available, and for clients who want ongoing growth, the store connects directly to our SEO and performance marketing services.'],
  ],
  'faqHeading' => 'Shopify Development Questions',
  'faqHeadingMuted' => 'From UAE Business Owners.',
  'faqs' => [
    ['question' => 'Why should I choose Shopify instead of a custom-built e-commerce site?', 'answer' => 'Shopify gives you a strong balance of launch speed, flexibility, and long-term manageability. It goes live significantly faster than a custom build, supports UAE payment gateways natively, and lets your team manage the store day to day without a developer. Most UAE e-commerce businesses, from single-product brands to large catalogs, have everything they need within Shopify’s platform without the cost and timeline of a full custom build.'],
    ['question' => 'Can you integrate UAE payment gateways like Telr and PayTabs?', 'answer' => 'Yes. We integrate Telr, PayTabs, Network International, and Checkout.com for UAE Shopify stores. Each gateway has different API, testing, and checkout requirements, so we configure and test the selected payment method as part of the store build before launch.'],
    ['question' => 'What is Shopify Plus and does my UAE business need it?', 'answer' => 'Shopify Plus is the enterprise tier for high-volume stores that need features such as advanced checkout customization, Shopify Flow automation, wholesale B2B channels, multi-currency capabilities, and dedicated platform support. Most new UAE stores do not need Plus immediately, so we build standard Shopify stores with a clear upgrade path for future growth.'],
    ['question' => 'Can you migrate my existing WooCommerce or Magento store to Shopify?', 'answer' => 'Yes. We can migrate products, customer records, order history, and essential store data from WooCommerce or Magento to Shopify. Existing SEO URLs are mapped with redirects to help preserve search visibility. The final migration scope and timeline depend on your current platform, data quality, integrations, and catalogue size.'],
    ['question' => 'How much does Shopify development cost in Dubai?', 'answer' => 'Shopify development cost in Dubai depends on whether the project uses a configured premium theme or a fully custom Shopify theme, as well as catalogue size, UAE payment gateway integration, custom apps, migration requirements, and Shopify Plus functionality. We provide a fixed-price proposal after discovery so the complete scope and cost are clear before work begins.'],
  ],
  'ctaHeading' => 'Ready to Launch Your Shopify Store',
  'ctaHeadingMuted' => 'in the UAE?',
  'ctaCopy' => 'Get a free consultation and we will show you exactly what your Shopify store should look like, how long it will take to build, and what it will cost. No obligation.',
];

require __DIR__ . '/service-page-template.php';
