<?php
$pageTitle = 'Terms & Conditions | Optimizers UAE';
$pageDescription = 'Terms and Conditions governing the Optimizers UAE website and digital marketing services.';
$isLegalPage = true;
require __DIR__ . '/header/header.php';
?>
<main class="op-legal">
  <section class="op-legal__hero"><div class="op-legal__hero-inner"><span class="op-legal__eyebrow">Legal &amp; Business</span><h1>Terms and <span>Conditions.</span></h1><p>The terms governing our website, services and working relationship with clients.</p><div class="op-legal__meta"><span>Optimizers UAE</span><span>Last updated: August 2026</span></div></div></section>
  <section class="op-legal__body">
    <aside class="op-legal__toc" aria-label="Terms and conditions contents"><strong>On this page</strong><a href="#who">Who we are</a><a href="#our-services">Our services</a><a href="#accepting">Accepting these terms</a><a href="#responsibilities">Client responsibilities</a><a href="#payments">Payments and fees</a><a href="#refunds">Refund policy</a><a href="#results">Results disclaimer</a><a href="#ip">Intellectual property</a><a href="#confidentiality">Confidentiality</a><a href="#platforms">Third-party platforms</a><a href="#website-use">Website use</a><a href="#liability">Liability</a><a href="#termination">Termination</a><a href="#law">Governing law</a><a href="#term-changes">Changes</a><a href="#terms-contact">Contact us</a></aside>
    <article class="op-legal__content">
      <section id="who"><span class="op-legal__number">01</span><h2>Who we are</h2><p>We are <strong>Optimizers</strong>, a digital marketing agency based in Dubai, UAE. We provide SEO, performance marketing, social media marketing, web development, branding and design services across all seven UAE emirates.</p><p>By using our website or hiring our services, you agree to these Terms and Conditions.</p></section>
      <section id="our-services"><span class="op-legal__number">02</span><h2>Our services</h2><h3>SEO</h3><p>Technical, on-page, off-page, local, e-commerce, international and multilingual SEO; keyword research; semantic content; and AI SEO.</p><h3>Performance and social marketing</h3><p>Google Ads, social media advertising, WhatsApp and email marketing across Meta, TikTok, Snapchat, YouTube and LinkedIn.</p><h3>Web, branding and design</h3><p>WordPress, Shopify and custom development; graphic design, content, reels, business branding and video editing.</p><p>Your individual proposal or service agreement defines the specific scope, deliverables, timeline and pricing and applies alongside these terms.</p></section>
      <section id="accepting"><span class="op-legal__number">03</span><h2>Accepting these terms</h2><p>By visiting optimizers.ae, submitting a form, requesting an audit or signing a service agreement, you confirm you have read and accepted these terms. If acting for a business, you confirm you have authority to bind it.</p></section>
      <section id="responsibilities"><span class="op-legal__number">04</span><h2>Client responsibilities</h2><ul><li>Provide accurate business information, goals and requirements</li><li>Provide feedback, approvals, content and necessary platform access on time</li><li>Ensure supplied content and assets are owned or properly licensed</li><li>Notify us of changes affecting delivery</li><li>Pay invoices by their stated due dates</li></ul><p>Client-caused delays, withheld access or missing approvals may affect delivery timelines.</p></section>
      <section id="payments"><span class="op-legal__number">05</span><h2>Payments and fees</h2><h3>Service fees</h3><p>Fees and payment terms are agreed in writing before work begins.</p><h3>Retainers and projects</h3><p>Monthly retainers are billed at the start of each month. Project work generally requires a deposit, with the balance due at completion or agreed milestones.</p><h3>Advertising budgets</h3><p>Platform ad spend is separate from management fees and is paid directly to the platform or invoiced as a pass-through cost.</p><h3>Late payment and currency</h3><p>Overdue invoices may result in paused services after notice. Fees are quoted in AED unless otherwise agreed.</p></section>
      <section id="refunds"><span class="op-legal__number">06</span><h2>Refund policy</h2><p>Monthly retainer fees are non-refundable once work for that period begins. Project deposits become non-refundable after design or development starts. If a prepaid project is cancelled before work begins, unused fees will be refunded. Spent advertising budgets cannot be refunded by Optimizers.</p><p>Report suspected billing errors within 14 days at <a href="mailto:contact@optimizers.ae">contact@optimizers.ae</a>.</p></section>
      <section id="results"><span class="op-legal__number">07</span><h2>Results and performance disclaimer</h2><p>We apply professional strategies and provide realistic expectations, but cannot guarantee rankings, traffic, leads, sales, follower growth or return figures. Results depend on market conditions, platform algorithms, competition, audience behavior, budgets and other factors outside our control.</p></section>
      <section id="ip"><span class="op-legal__number">08</span><h2>Intellectual property</h2><p>Your supplied materials remain yours. Work created specifically for you becomes your property after full payment. Our pre-existing website content, templates, processes, tools and methodologies remain Optimizers property. Third-party assets remain subject to their respective licences.</p></section>
      <section id="confidentiality"><span class="op-legal__number">09</span><h2>Confidentiality</h2><p>We treat client business information, strategies and campaign data as confidential except where disclosure is necessary for service delivery or required by UAE law. Clients must likewise protect Optimizers’ confidential strategies, pricing, tools and processes.</p></section>
      <section id="platforms"><span class="op-legal__number">10</span><h2>Third-party platforms</h2><p>Google, Meta, TikTok, LinkedIn, WhatsApp, WordPress, Shopify and other platforms operate under their own terms. We are not responsible for their policy, algorithm, system or account-access decisions.</p></section>
      <section id="website-use"><span class="op-legal__number">11</span><h2>Using our website</h2><ul><li>Use the website only for lawful purposes</li><li>Do not hack, damage or disrupt the website</li><li>Do not scrape or reproduce content without written permission</li><li>Do not submit false or misleading information</li></ul></section>
      <section id="liability"><span class="op-legal__number">12</span><h2>Limitation of liability</h2><p>To the fullest extent permitted by UAE law, Optimizers is not liable for indirect or consequential loss, lost revenue or opportunity, third-party platform decisions, or problems caused by inaccurate client data. Our total liability will not exceed the amount paid to us in the three months preceding a claim.</p></section>
      <section id="termination"><span class="op-legal__number">13</span><h2>Termination</h2><p>Clients may terminate monthly retainers with 30 days’ written notice before the next billing date. Optimizers may terminate services with notice for non-payment, breach or unlawful requests, and immediately for serious breaches. Paid completed work and credentials will be transferred at termination; outstanding invoices remain due.</p></section>
      <section id="law"><span class="op-legal__number">14</span><h2>Governing law</h2><p>These terms are governed by UAE law. Disputes are subject to the jurisdiction of the courts of Dubai, UAE.</p></section>
      <section id="term-changes"><span class="op-legal__number">15</span><h2>Changes to these terms</h2><p>We may update these terms as services, legal requirements or business practices change. The revised effective date will be shown on this page.</p></section>
      <section id="terms-contact"><span class="op-legal__number">16</span><h2>Contact us</h2><div class="op-legal__contact-grid"><p><small>Company</small><strong>Optimizers</strong></p><p><small>Website</small><a href="https://optimizers.ae/">optimizers.ae</a></p><p><small>Address</small><strong>Office JVC, Dubai, UAE</strong></p><p><small>Phone</small><a href="tel:+971 50 781 8373">+971 50 781 83733</a></p><p><small>Email</small><a href="mailto:contact@optimizers.ae">contact@optimizers.ae</a></p><p><small>WhatsApp</small><a href="https://wa.me/971507818373">+971 50 781 83733</a></p></div></section>
    </article>
  </section>
</main>
<?php require __DIR__ . '/footer/footer.php'; ?>
