<?php
$servicePage = [
  'slug' => 'wordpress-development',
  'pageTitle' => 'WordPress Development Company Dubai | UAE | Optimizers',
  'pageDescription' => 'Custom WordPress development services in Dubai for fast, secure, SEO-ready websites with clean code and an easy-to-manage CMS for UAE businesses.',
  'heroIcon' => 'assets/icons/service-pages/wordpress.svg',
  'heroEyebrow' => 'WordPress Development',
  'heroHeading' => 'WordPress Development in Dubai',
  'heroHeadingMuted' => 'for UAE Businesses That Want Results',
  'heroDescription' => 'We build fast, secure, and conversion-focused WordPress websites for UAE businesses across every industry. As a dedicated WordPress development company in Dubai, our team delivers custom WordPress development services in Dubai from discovery through launch, with clean code, SEO-ready structure, and a CMS your team can actually manage without needing a developer on call.',
  'auditLabel' => 'Get a Free WordPress Audit',
  'heroMeta' => ['YOURBUSINESS.AE · WORDPRESS · CUSTOM THEMES', 'FAST LOADING · SECURE'],
  'overviewEyebrow' => 'What Is WordPress Development',
  'overviewHeading' => 'WordPress Development,',
  'overviewHeadingMuted' => 'Explained Simply.',
  'overviewCopy' => 'WordPress development is the process of building a website on WordPress, the world’s most widely used CMS (Content Management System), through custom theme creation, plugin configuration, and SEO-optimized page architecture that makes the site both performant and manageable. Custom WordPress development goes beyond installing a template. It means building a site around your specific business goals, audience, and brand identity, so the result is a platform that grows with you rather than one you outgrow within a year.',
  'stats' => [
    ['value' => '200+', 'label' => 'UAE Clients'],
    ['value' => '5.0', 'label' => 'Google Rating'],
  ],
  'includedHeading' => 'What Our WordPress Development',
  'includedHeadingMuted' => 'Service Covers.',
  'includedCopy' => 'Every build goes through the same complete process, not a stripped-down version to hit a lower price.',
  'included' => [
    ['title' => 'Custom WordPress Theme Development', 'icon' => 'assets/icons/service-pages/wordpress.svg'],
    ['title' => 'WordPress CMS Setup & Configuration', 'icon' => 'assets/icons/service-pages/wordpress.svg'],
    ['title' => 'WordPress Plugin Development & Integration', 'icon' => 'assets/icons/service-pages/code.svg'],
    ['title' => 'Responsive & Mobile-First Build', 'icon' => 'assets/icons/service-pages/mobile.svg'],
    ['title' => 'WordPress E-Commerce Development', 'icon' => 'assets/icons/service-pages/woocommerce.svg'],
    ['title' => 'On-Page SEO & Core Web Vitals Foundation', 'icon' => 'assets/icons/service-pages/support.svg'],
    ['title' => 'WordPress Custom Landing Page Development', 'icon' => 'assets/icons/service-pages/mobile.svg'],
    ['title' => 'AI-Ready WordPress Development', 'icon' => 'assets/icons/service-pages/code.svg'],
  ],
  'whyHeading' => 'Why WordPress Web Development in Dubai',
  'whyHeadingMuted' => 'Makes Sense for Your Business.',
  'why' => [
    ['title' => 'You Own Full Control Without a Developer', 'copy' => 'A properly built WordPress CMS means your team updates pages, publishes content, and manages the site day to day without billing a developer for every small change.'],
    ['title' => 'Built-In SEO Advantage From Launch', 'copy' => 'WordPress’s architecture supports clean URL structure, fast load times, and easy schema implementation, giving your SEO team a strong foundation before any optimization work begins.'],
    ['title' => 'Scales as Your Business Grows', 'copy' => 'New service pages, new locations, new products, new languages. A custom WordPress build scales in any direction without requiring a rebuild from scratch.'],
    ['title' => 'Bespoke Builds That Stand Apart', 'copy' => 'Bespoke WordPress development means no other UAE business is running the same template. Every design decision, layout, and feature reflects your brand specifically rather than a shared starting point.'],
  ],
  'processHeading' => 'How We Approach WordPress Development',
  'processHeadingMuted' => 'in Dubai.',
  'process' => [
    ['title' => 'Discovery & Requirements', 'copy' => 'We learn your business goals, target audience, required features, and competitive landscape before touching a line of code.'],
    ['title' => 'UI/UX Design & Wireframing', 'copy' => 'We design every page layout for approval before development begins, so there are zero design surprises after build starts.'],
    ['title' => 'Custom Theme & Plugin Development', 'copy' => 'We build your custom WordPress theme and configure or develop the plugins your site genuinely needs.'],
    ['title' => 'Speed, Security & SEO Testing', 'copy' => 'We test every page for Core Web Vitals, mobile responsiveness, security hardening, and on-page SEO before launch.'],
    ['title' => 'Launch, Training & Support', 'copy' => 'We launch the site and walk your team through managing content, with ongoing support available after handoff.'],
  ],
  'faqHeading' => 'WordPress Development Questions',
  'faqHeadingMuted' => 'From UAE Business Owners.',
  'faqs' => [
    ['question' => 'What is the difference between custom WordPress development and a theme-based build?', 'answer' => 'A theme-based build adapts an existing template, so it is usually faster and cheaper but can look similar to other websites. Custom WordPress development creates the theme, layout, and code around your brand, giving your UAE business a distinctive website with stronger control over performance, functionality, and SEO.'],
    ['question' => 'What is custom WordPress theme development and do I need it?', 'answer' => 'Custom WordPress theme development means building your site’s visual design and code from scratch or from a clean starter base, rather than applying a pre-designed template. UAE businesses that need a specific look, unique functionality, or strong SEO performance generally benefit from a custom theme over an off-the-shelf solution.'],
    ['question' => 'Can you build WordPress e-commerce stores for UAE businesses?', 'answer' => 'Yes. We build WooCommerce stores for UAE B2C and B2B businesses, including UAE payment gateway integrations and custom product catalogue structures. When Shopify is a better fit, our Shopify development team can recommend and build that platform instead.'],
    ['question' => 'Do you offer WordPress development services in Abu Dhabi and Sharjah, not just Dubai?', 'answer' => 'Yes. We serve businesses across all seven UAE emirates. Our WordPress development services cover Dubai, Abu Dhabi, Sharjah, Ajman, Ras Al Khaimah, Fujairah, and Umm Al Quwain.'],
    ['question' => 'How much does WordPress website development cost in Dubai?', 'answer' => 'A standard business WordPress website in Dubai typically starts from AED 5,000. Custom e-commerce, multilingual, or advanced-functionality builds cost more, while WordPress e-commerce projects generally start from AED 8,000 to AED 15,000 depending on catalogue size, payment integrations, and required features. We provide a fixed-price proposal after reviewing your requirements.'],
    ['question' => 'What determines the WordPress development price for a UAE project?', 'answer' => 'The main pricing factors are page count, custom theme requirements, plugin and third-party integrations, e-commerce functionality, multilingual support, and overall development complexity. Every proposal includes a clear WordPress development cost breakdown before work begins.'],
    ['question' => 'How long does WordPress web development in Dubai take?', 'answer' => 'A standard business website usually takes 4 to 6 weeks from design approval to launch. Complex custom WordPress websites with e-commerce or advanced functionality typically take 8 to 12 weeks. The agreed timeline is included in the project proposal.'],
  ],
  'ctaHeading' => 'Ready to Build a WordPress Website',
  'ctaHeadingMuted' => 'That Actually Works for Your Business?',
  'ctaCopy' => 'Whether you need a clean business website, a custom e-commerce store, or a bespoke WordPress built from scratch, our WordPress development team in Dubai is ready to start. We serve businesses across Dubai, Abu Dhabi, and all seven UAE emirates.',
];

require __DIR__ . '/service-page-template.php';
