<section class="op-coverage" id="coverage" aria-labelledby="coverage-title">
  <div class="op-coverage__inner">
    <header class="op-coverage__head" data-reveal>
      <div>
        <span class="op-coverage__eyebrow">Our Coverage</span>
        <h2 id="coverage-title">Digital marketing services across <span>all 7 UAE Emirates</span></h2>
      </div>
      <p>We are a UAE-based agency with on-ground experience in every emirate. Your location is where your buyers live, your competitors operate, and your local search presence needs to be strongest. We bring emirate-specific knowledge to every campaign.</p>
    </header>

    <div class="op-coverage__grid">
      <article class="op-emirate" data-index="01" data-reveal><span class="op-emirate__icon" aria-hidden="true"><svg viewBox="0 0 32 32"><path d="M7 27h18M10 27V7h12v20M14 11h1M18 11h1M14 15h1M18 15h1M14 19h1M18 19h1M15 27v-4h2v4"/></svg></span><h3>Dubai</h3><span class="op-emirate__tag">HQ and primary market</span><p>Dubai is our home base and the UAE’s most competitive digital market. We deliver SEO, Google Ads, social media, and web development across every industry, from Downtown and Business Bay to JLT, Dubai Marina, and Al Quoz.</p></article>
      <article class="op-emirate" data-index="02" data-reveal><span class="op-emirate__icon" aria-hidden="true"><svg viewBox="0 0 32 32"><path d="M7 27h18M10 27V7h12v20M14 11h1M18 11h1M14 15h1M18 15h1M14 19h1M18 19h1M15 27v-4h2v4"/></svg></span><h3>Abu Dhabi</h3><span class="op-emirate__tag">Capital region</span><p>Abu Dhabi’s corporate, government, and tourism sectors demand a specific approach. We understand the market dynamics and build campaigns that match how Abu Dhabi buyers and businesses search and decide.</p></article>
      <article class="op-emirate" data-index="03" data-reveal><span class="op-emirate__icon" aria-hidden="true"><svg viewBox="0 0 32 32"><path d="M7 27h18M10 27V7h12v20M14 11h1M18 11h1M14 15h1M18 15h1M14 19h1M18 19h1M15 27v-4h2v4"/></svg></span><h3>Sharjah</h3><span class="op-emirate__tag">Cultural and commercial hub</span><p>Sharjah is a fast-growing market for education, retail, and manufacturing. Our local SEO and paid media strategies reflect how Sharjah consumers search and what motivates purchasing decisions.</p></article>
      <article class="op-emirate" data-index="04" data-reveal><span class="op-emirate__icon" aria-hidden="true"><svg viewBox="0 0 32 32"><path d="M7 27h18M10 27V7h12v20M14 11h1M18 11h1M14 15h1M18 15h1M14 19h1M18 19h1M15 27v-4h2v4"/></svg></span><h3>Ajman</h3><span class="op-emirate__tag">Emerging market</span><p>Ajman’s business community is growing across retail, real estate, and services. We help local businesses get found online and build a presence that competes across emirate borders.</p></article>
      <article class="op-emirate" data-index="05" data-reveal><span class="op-emirate__icon" aria-hidden="true"><svg viewBox="0 0 32 32"><path d="M7 27h18M10 27V7h12v20M14 11h1M18 11h1M14 15h1M18 15h1M14 19h1M18 19h1M15 27v-4h2v4"/></svg></span><h3>Ras Al Khaimah</h3><span class="op-emirate__tag">Northern UAE</span><p>RAK’s tourism growth, industrial expansion, and hotel development create opportunities for strong digital marketing. We run SEO, paid media, and social campaigns for local and international audiences.</p></article>
      <article class="op-emirate" data-index="06" data-reveal><span class="op-emirate__icon" aria-hidden="true"><svg viewBox="0 0 32 32"><path d="M7 27h18M10 27V7h12v20M14 11h1M18 11h1M14 15h1M18 15h1M14 19h1M18 19h1M15 27v-4h2v4"/></svg></span><h3>Fujairah</h3><span class="op-emirate__tag">East coast</span><p>Fujairah’s port economy and tourism sector are expanding. We serve businesses with SEO, social media, and performance campaigns built for the East Coast market and its distinct buyer audience.</p></article>
      <article class="op-emirate" data-index="07" data-reveal><span class="op-emirate__icon" aria-hidden="true"><svg viewBox="0 0 32 32"><path d="M7 27h18M10 27V7h12v20M14 11h1M18 11h1M14 15h1M18 15h1M14 19h1M18 19h1M15 27v-4h2v4"/></svg></span><h3>Umm Al Quwain</h3><span class="op-emirate__tag">Northern Emirates</span><p>Businesses in Umm Al Quwain benefit from marketing that captures local buyers and reaches neighboring emirates. We extend campaign reach without losing local relevance.</p></article>
    </div>
  </div>
</section>
